### ISSUE TITLE
Support gap: prime login --env staging throw Exception on WSL2 (Ubuntu on Windows)

### ISSUE THREAD

**Issue by JFU-NAVA-PBC** [CDCgov/prime-reportstream#10776]
### User Story

As a report stream developer, I want prime CLI works on all main OS - including WSL2 (Windows Linux Subsystem)

### Description/Use Case

prime login --env staging (or prod, demo), throw Unsupported Exception on WSL2
==========
./prime login --env staging
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/home/jfu/RS10706-swagger-ui-authorization-methods/prime-router/build/libs/prime-router-0.2-SNAPSHOT-all.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
About to launch a browser to log in to Okta...
Exception in thread "main" java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
        at java.desktop/java.awt.Desktop.checkActionSupport(Desktop.java:380)
        at java.desktop/java.awt.Desktop.browse(Desktop.java:524)
        at gov.cdc.prime.router.cli.LoginCommand.launchSignIn(OktaCommands.kt:86)
        at gov.cdc.prime.router.cli.LoginCommand.run(OktaCommands.kt:72)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
        at gov.cdc.prime.router.cli.MainKt.main(main.kt:296)

=================

### Risks/Impacts/Considerations

None

### Dev Notes

May be a JDK platform support issue, need to triage and find out

### Acceptance Criteria

The root cause identified, a solution found or work around found or no feasible solution - then document the issue.

**Comment by bishoyayoub** [comment]
@JFU-NAVA-PBC  Please move to ready for grooming or let me know if we should icebox this story.

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10776?planning-poker) with Zenhub @arnejduranovic @brick-green @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @thetaurean @jack-h-wang
