### ISSUE TITLE
Improve primeCLI login error report

### ISSUE THREAD

**Issue by JFU-NAVA-PBC** [CDCgov/prime-reportstream#11437]
### User Story

As a platform developer, I use primeCLI: prime login --env to perform dev work, e.g. obtain an access token, I want the error message showing useful details when the login failed, for example, I got okta access denied error response, but that error message is swallowed and did not either show in browser or print out at stdout:

`Listening for transport dt_socket at address: 10099
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/Users/jimfuqian-mac-pro/RS11401-Update-and-test-Okta-migration-backend-validation/prime-router/build/libs/prime-router-0.2-SNAPSHOT-all.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
About to launch a browser to log in to Okta...
Exception in thread "main" java.lang.IllegalStateException: Invalid authentication
	at gov.cdc.prime.router.cli.LoginCommand.launchSignIn(OktaCommands.kt:93)
	at gov.cdc.prime.router.cli.LoginCommand.run(OktaCommands.kt:72)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
	at gov.cdc.prime.router.cli.MainKt.main(main.kt:297)`

**Comment by arnejduranovic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/gh/CDCgov/prime-reportstream/11437?planning-poker) with Zenhub @adegolier @JFisk42 @kant777 @wcutshall
