### ISSUE TITLE
Regular 401s from React

### ISSUE THREAD

**Issue by adegolier** [CDCgov/prime-reportstream#11585]
## Describe the bug
We are frequently getting numerous 401 errors when calls are being made to 	`GET https://prime.cdc.gov/api/settings/organizations/[some organization]` Weirdly, it only seems to be one at any given time, but it will sometimes come in waves of like 10+ errors. An example can be seen today 9/29/2023 between the server hours of 10:35 and 10:50 it was for `co-san-juan-basin-phd`, but I have also seen this happen for the `ignore` organization and others.

## Impact on ReportStream
Unsure the entire extent of the impact. 401 indicates unauthorized, which implies an issue with authorization to retrieve settings of our own app. It also causes numerous PagerDuty alerts to whoever is on call.

## Steps to reproduce
Unsure how to reproduce, as it is an intermittent error.

## Expected behavior
We shouldn't be having issues authenticating with our own server.

## Logs

> Error: React Router caught the following error during render
>     at e.<computed> [as error] (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:2033:2368)
>     at NIe.componentDidCatch (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:64:3703)
>     at Gce.o.componentDidCatch.n.callback (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:40:772)
>     at RJ (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:38:9910)
>     at YJ (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:40:31954)
>     at ade (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:40:31534)
>     at ade (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:40:31441)
>     at sNe (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:40:31081)
>     at dNe (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:40:41020)
>     at c1 (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:40:40371)

> {"error":"React Router caught the following error during render","location":"https://reportstream.cdc.gov/","other":[{"name":"unauthorized","data":{"error":"Unauthorized"},"originalError":{"message":"Request failed with status code 401","name":"AxiosError","stack":"AxiosError: Request failed with status code 401\n    at qOt (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:5203:1055)\n    at XMLHttpRequest.f (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:5203:4218)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":"xhr","transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","x-ms-session-id":"","authentication-type":"okta","authorization":"Bearer ","organization":"co-san-juan-basin-phd"},"method":"get","url":"https://prime.cdc.gov/api/settings/organizations/co-san-juan-basin-phd"},"code":"ERR_BAD_REQUEST","status":401}},{"componentStack":"\n    at Du (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:45:11388)\n    at Suspense\n    at p_t (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:5011:12830)\n    at cCt (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:5203:15239)\n    at N4t (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:5201:1227)\n    at aht (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:4899:12668)\n    at NPt (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:5274:55455)\n    at THe (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:2053:250)\n    at t (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:4899:24073)\n    at RPt (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:5274:55481)\n    at FPt (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:5274:57508)\n    at i7t\n    at RIe (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:64:4003)\n    at NIe (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:64:3266)\n    at BIe (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:64:7449)\n    at HIe (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:64:7860)\n    at UIe (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:64:6599)\n    at Suspense\n    at KNe (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:40:67514)\n    at vRe (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:45:8613)\n    at Vde (https://reportstream.cdc.gov/assets/app/index-07f8a750.js:45:15562)"}]}

**Comment by adegolier** [comment]
A few more today (10/2/2023) between 9:10 and 11:00 am Eastern (same as server).
