### ISSUE TITLE
The endpoint check function doesn't work for flexion.

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-reportstream#11621]
Note, the curl command below is also working with REST check.  However, the endpoint works with staging when sending a test message to RS and it routes to Flexion correctly.

$ curl "http://localhost:7071/api/check?sftpcheck=flexion.etor-service-receiver"
flexion.etor-service-receiver: is a valid receiver
**** Receiver Status: ACTIVE
flexion.etor-service-receiver: REST Transport
Attempting to authenticate at: https://cdcti-staging-api2.azurewebsites.net/v1/auth/token
flexion.etor-service-receiver: Client request(POST https://cdcti-staging-api2.azurewebsites.net/v1/auth/token) invalid: 401 Unauthorized. Text: "{"error":"io.jsonwebtoken.MalformedJwtException: JWT strings must contain exactly 2 period characters. Found: 0"}": No root cause
io.ktor.client.plugins.ClientRequestException: Client request(POST https://cdcti-staging-api2.azurewebsites.net/v1/auth/token) invalid: 401 Unauthorized. Text: "{"error":"io.jsonwebtoken.MalformedJwtException: JWT strings must contain exactly 2 period characters. Found: 0"}"
        at io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:54)
        at io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
        at io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
        at io.ktor.client.plugins.HttpCallValidator.validateResponse(HttpCallValidator.kt:51)
        at io.ktor.client.plugins.HttpCallValidator.access$validateResponse(HttpCallValidator.kt:43)
        at io.ktor.client.plugins.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:152)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at gov.cdc.prime.router.azure.CheckFunction.testRest(CheckFunction.kt:357)
        at gov.cdc.prime.router.azure.CheckFunction.testTransport(CheckFunction.kt:316)
        at gov.cdc.prime.router.azure.CheckFunction.run(CheckFunction.kt:120)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
        at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:22)
        at com.microsoft.azure.functions.worker.chain.FunctionExecutionMiddleware.invoke(FunctionExecutionMiddleware.java:19)
        at com.microsoft.azure.functions.worker.chain.InvocationChain.doNext(InvocationChain.java:21)
        at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:125)
        at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:34)
        at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
        at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:44)
        at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:94)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by oslynn** [comment]
Done.
