### ISSUE TITLE
Improve prime CLI login to support multiple ENVs simultaneously

### ISSUE THREAD

**Issue by JFU-NAVA-PBC** [CDCgov/prime-reportstream#12766]
### User Story

As report stream backend developer, I want prime CLI login command allow login to PROD, STAGING, TEST etc. at the same period of time, currently when login into a specific ENV e.g. STAGING, the token is saved under ~./.prime/accessToken.json, if switch to login into another ENV say PROD, the saved token will be used which is not good for PROD, it will throw error as below:

Exception in thread "main" java.lang.IllegalStateException: Unable to obtain Okta access token for environment STAGING
	at gov.cdc.prime.router.cli.CommandUtilities$Companion.isApiAvailable$prime_router(CommandUtilities.kt:68)
	at gov.cdc.prime.router.cli.CommandUtilities$Companion.isApiAvailable$prime_router$default(CommandUtilities.kt:65)
	at gov.cdc.prime.router.cli.SettingCommand.checkApi(SettingCommands.kt:548)
	at gov.cdc.prime.router.cli.GetMultipleSettings.run(SettingCommands.kt:1004)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
	at gov.cdc.prime.router.cli.MainKt.main(main.kt:307)

### Description/Use Case

It is desirable to support development of multiple ENVs during the same period of time - e.g.- one hour

### Risks/Impacts/Considerations

No

### Dev Notes

the recommended approach:
either tag the accessToken.json with ENV name, e.g. accessToken.staging.json, accessToken.prod.json

OR

persist the accessToken.json in a ENV specific sub dir under ~/.prime/, e.g. ~/.prime/prod, ~/.prime/staging, etc.

and a plus:

Also it is nice to save the incumbant accessToken.json as accessToken.json.<timestamp> when new accessToken.json come in.

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12766?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @jalbinson @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @mkalish @thetaurean
