### ISSUE TITLE
Exception threw in production and need to be addressed.

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-reportstream#13233]
https://portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%2C%22ResourceGroup%22%3A%22prime-data-hub-prod%22%2C%22Name%22%3A%22pdhprod-appinsights%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F7d1e3999-6577-4cd5-b296-f518e5c8e677%252FresourceGroups%252Fprime-data-hub-prod%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252Fpdhprod-appinsights%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel~/%7B%22eventId%22%3A%22ce42b32c-c1d9-11ee-ba95-000d3a8d3a3d%22%2C%22timestamp%22%3A%222024-02-02T14%3A44%3A50.525Z%22%2C%22cacheId%22%3A%2213912e9f-8c33-4aa7-a346-7bbf91ec7061%22%2C%22eventTable%22%3A%22exceptions%22%2C%22timeContext%22%3A%7B%22durationMs%22%3A86400000%2C%22endTime%22%3A%222024-02-02T17%3A51%3A51.486Z%22%7D%7D

Exception while executing function: Functions.convert-fhir Result: Failure
Exception: NoSuchElementException:
Stack: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor444.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
	at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:22)
	at com.microsoft.azure.functions.worker.chain.FunctionExecutionMiddleware.invoke(FunctionExecutionMiddleware.java:19)
	at com.microsoft.azure.functions.worker.chain.InvocationChain.doNext(InvocationChain.java:21)
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:125)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:34)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:44)
	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:94)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.util.NoSuchElementException
	at tech.tablesaw.api.Row.next(Row.java:518)
	at tech.tablesaw.api.Table$1.next(Table.java:1467)
	at tech.tablesaw.api.Table$1.next(Table.java:1461)
	at gov.cdc.prime.router.fhirengine.engine.LookupTableValueSet$mapVal$2.invoke(LookupTableValueSet.kt:65)
	at gov.cdc.prime.router.fhirengine.engine.LookupTableValueSet$mapVal$2.invoke(LookupTableValueSet.kt:31)

**Comment by chris-kuryak** [comment]
Victor is reviewing to see if this is still needed

**Comment by chris-kuryak** [comment]
This is being fixed in #16863
