### ISSUE TITLE
High number of failures in the translate-fhir function in Staging

### ISSUE THREAD

**Issue by adegolier** [CDCgov/prime-reportstream#13359]
## Describe the bug
Nearly 200 failures in the translate-fhir function in Staging beginning between 4 and 5PM eastern on 2/12.

Exception:
`Exception while executing function: Functions.translate-fhir Result: Failure
Exception: RequiredElementException: Required element message-headers conditional was false or value was empty.
Stack: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor229.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
	at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:22)
	at com.microsoft.azure.functions.worker.chain.FunctionExecutionMiddleware.invoke(FunctionExecutionMiddleware.java:19)
	at com.microsoft.azure.functions.worker.chain.InvocationChain.doNext(InvocationChain.java:21)
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:125)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:34)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:44)
	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:94)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: gov.cdc.prime.router.fhirengine.translation.hl7.schema.ConfigSchemaElementProcessingException: Error encountered while applying: message-headers in /metadata/hl7_mapping/receivers/Flexion/TILabOrder.yml to FHIR bundle. 
Error was: Required element message-headers conditional was false or value was empty.
	at gov.cdc.prime.router.fhirengine.translation.hl7.FhirToHl7Converter.processSchema(FhirToHl7Converter.kt:123)
	at gov.cdc.prime.router.fhirengine.translation.hl7.FhirToHl7Converter.processSchema$default(FhirToHl7Converter.kt:101)
	at gov.cdc.prime.router.fhirengine.translation.hl7.FhirToHl7Converter.convert(FhirToHl7Converter.kt:91)
	at gov.cdc.prime.router.fhirengine.engine.FHIRTranslator.getHL7MessageFromBundle$prime_router(FHIRTranslator.kt:206)
	at gov.cdc.prime.router.fhirengine.engine.FHIRTranslator.getByteArrayFromBundle$prime_router(FHIRTranslator.kt:179)
	at gov.cdc.prime.router.fhirengine.engine.FHIRTranslator.doWork(FHIRTranslator.kt:87)
	at gov.cdc.prime.router.fhirengine.engine.FHIREngine.run(FHIREngine.kt:201)
	at gov.cdc.prime.router.fhirengine.azure.FHIRFunctions$runFhirEngine$newMessages$1.invoke(FHIRFunctions.kt:159)
	at gov.cdc.prime.router.fhirengine.azure.FHIRFunctions$runFhirEngine$newMessages$1.invoke(FHIRFunctions.kt:158)
	at gov.cdc.prime.router.azure.DatabaseAccess.transactReturning$lambda$1(DatabaseAccess.kt:107)
	at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:531)
	at org.jooq.impl.Tools$3$1.block(Tools.java:6068)
	at java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465)
	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436)
	at org.jooq.impl.Tools$3.get(Tools.java:6065)
	at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:579)
	at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:503)
	at gov.cdc.prime.router.azure.DatabaseAccess.transactReturning(DatabaseAccess.kt:107)
	at gov.cdc.prime.router.fhirengine.azure.FHIRFunctions.runFhirEngine(FHIRFunctions.kt:158)
	at gov.cdc.prime.router.fhirengine.azure.FHIRFunctions.doTranslate(FHIRFunctions.kt:131)
	at gov.cdc.prime.router.fhirengine.azure.FHIRFunctions.doTranslate$default(FHIRFunctions.kt:125)
	at gov.cdc.prime.router.fhirengine.azure.FHIRFunctions.translate(FHIRFunctions.kt:116)
	... 17 more
Caused by: gov.cdc.prime.router.fhirengine.translation.hl7.RequiredElementException: Required element message-headers conditional was false or value was empty.
	at gov.cdc.prime.router.fhirengine.translation.hl7.FhirToHl7Converter.processElement$prime_router(FhirToHl7Converter.kt:201)
	at gov.cdc.prime.router.fhirengine.translation.hl7.FhirToHl7Converter.processSchema(FhirToHl7Converter.kt:121)
	... 38 more`

They all seem to be from flexion.etor-service-sender

An example can be seen in Azure [here](https://portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%2C%22ResourceGroup%22%3A%22prime-data-hub-staging%22%2C%22Name%22%3A%22pdhstaging-appinsights%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F7d1e3999-6577-4cd5-b296-f518e5c8e677%252FresourceGroups%252Fprime-data-hub-staging%252Fproviders%252Fmicrosoft.insights%252Fcomponents%252Fpdhstaging-appinsights%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel~/%7B%22cacheId%22%3A%2214ee19fb-498a-4155-a73b-c8e2290481dc%22%2C%22eventTable%22%3A%22traces%22%2C%22timeContext%22%3A%7B%22durationMs%22%3A86400000%2C%22endTime%22%3A%222024-02-13T15%3A15%3A44.705Z%22%7D%7D) though you may need to be logged in as SU to view.

## Impact on ReportStream
Flooding the on call with alerts, may have more significant impacts if root cause is pushed to production.

## Steps to reproduce
Unsure how to reproduce, but logs provided above.

**Comment by LaFreda1** [comment]
Issue had been fixed, closing.
