### ISSUE TITLE
Continue testing HL7 ingest

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1604]
Continuation of #1469

**Comment by san-nat** [comment]
List of Bad HL7 scenarios

Empty file
Csv file
Random text
Missing mandatory fields
Duplicate segments e.g. PID
Partially terminated 
Bad charset
special char
Wrong datatype e.g dob
More than 50mb post message body
Only header MSH

**Comment by san-nat** [comment]
in-progress 
a) above scenarios are covered by #1604
b) more exploratory HL7 ingest testing

**Comment by san-nat** [comment]
Tested with jurisdiction filters.

**Comment by san-nat** [comment]
Found a performance testing issue with single record HL7 submissions, related the connection #1744

`[2021-07-29T04:11:48.895Z] Error getting connection from data source HikariDataSource (HikariPool-2)
[2021-07-29T04:11:48.895Z] Result: Error getting connection from data source HikariDataSource (HikariPool-2)
[2021-07-29T04:11:48.895Z] Exception: Error getting connection from data source HikariDataSource (HikariPool-2)
[2021-07-29T04:11:48.895Z] Stack: org.jooq.exception.DataAccessException: Error getting connection from data source HikariDataSource (HikariPool-2)
[2021-07-29T04:11:48.895Z]      at org.jooq_3.15.0.POSTGRES.debug(Unknown Source)
[2021-07-29T04:11:48.895Z]      at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:90)
[2021-07-29T04:11:48.895Z]      at org.jooq.impl.DefaultExecuteContext.connection(DefaultExecuteContext.java:535)
[2021-07-29T04:11:48.895Z]      at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:295)
[2021-07-29T04:11:48.895Z]      at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:295)
[2021-07-29T04:11:48.895Z]      at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:316)
[2021-07-29T04:11:48.895Z]      at org.jooq.impl.SelectImpl.fetchLazyNonAutoClosing(SelectImpl.java:2866)
[2021-07-29T04:11:48.895Z]      at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:506)
[2021-07-29T04:11:48.895Z]      at gov.cdc.prime.router.azure.DatabaseAccess.fetchOrganizationAndSetting(DatabaseAccess.kt:361)
[2021-07-29T04:11:48.895Z]      at gov.cdc.prime.router.azure.SettingsFacade.findOrganizationAndReceiver(SettingsFacade.kt:142)
[2021-07-29T04:11:48.895Z]      at gov.cdc.prime.router.azure.SettingsFacade.findOrganizationAndReceiver(SettingsFacade.kt:67)
[2021-07-29T04:11:48.895Z]      at gov.cdc.prime.router.azure.ActionHistory.prettyPrintDestinationsJson(ActionHistory.kt:490)
[2021-07-29T04:11:48.895Z]      at gov.cdc.prime.router.azure.ReportFunction.createResponseBody(ReportFunction.kt:428)
[2021-07-29T04:11:48.895Z]      at gov.cdc.prime.router.azure.ReportFunction.run(ReportFunction.kt:118)
[2021-07-29T04:11:48.895Z]      at jdk.internal.reflect.GeneratedMethodAccessor330.invoke(Unknown Source)
[2021-07-29T04:11:48.895Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-07-29T04:11:48.896Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-07-29T04:11:48.896Z]      at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
[2021-07-29T04:11:48.896Z]      at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:55)
[2021-07-29T04:11:48.896Z]      at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:57)
[2021-07-29T04:11:48.896Z]      at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[2021-07-29T04:11:48.896Z]      at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[2021-07-29T04:11:48.896Z]      at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[2021-07-29T04:11:48.896Z]      at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[2021-07-29T04:11:48.896Z]      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-07-29T04:11:48.896Z]      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-07-29T04:11:48.896Z] 	at java.base/java.lang.Thread.run(Thread.java:829)
[2021-07-29T04:11:48.896Z] Caused by: java.sql.SQLTransientConnectionException: HikariPool-2 - Connection is not available, request timed out after 30001ms.
[2021-07-29T04:11:48.896Z] 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
[2021-07-29T04:11:48.896Z] 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:181)
[2021-07-29T04:11:48.896Z] 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146)
[2021-07-29T04:11:48.897Z] 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[2021-07-29T04:11:48.897Z] 	at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:87)
[2021-07-29T04:11:48.897Z] 	... 27 more
`

**Comment by san-nat** [comment]
![image](https://user-images.githubusercontent.com/3782910/127560905-2af650ca-f999-4f61-bcc4-5facece51d42.png)
