### ISSUE TITLE
FakeData generator bugs with default values in CODE and TABLES

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1733]
1.   BUG:	in fake data generator defaults don't work with TABLE types.    Recreate by having a schema with a TABLE type field, with a default value that is a valid lookup in that table.    Fake Data generator throws an exception.
2.  Same bug, with CODE types.
3. fake data generator does not know about the zip-code-data table.    See FakeReport.kt:: createFakeTableValue.

Credit to @jbiskie for finding these errors.

Note:
If you have a schema that has a field that is a table and also has a default value, the fake data generator blows up even though the default value is a valid value in that table.
Fake data generator is tested with the test integration work item in gradle. 

To run test integration:
`./gradlew testIntegration`

AC:
* Reproduce the error and verify that it is still a problem.
* Resolve this error if it still exists.
* Add a test to the quickTest in the integration test suite that makes the call that is causing this error. (There are no unit tests around fake data generator, add it to test integration)

**Comment by jimduff-usds** [comment]
How to generate problem #3:

How to reproduce:   

$ ./prime data --input-fake 100 --input-schema ipatientCare/reddyfmc-la-covid-19 --output ./fake-reddy.csv

Loaded schema and receivers
Exception in thread "main" kotlin.NotImplementedError: An operation is not implemented: Add this table
	at gov.cdc.prime.router.FakeDataService.getFakeValueForElement$createFakeTableValue(FakeReport.kt:150)
	at gov.cdc.prime.router.FakeDataService.getFakeValueForElement(FakeReport.kt:169)
	at gov.cdc.prime.router.FakeReport.buildColumn$prime_router(FakeReport.kt:249)
	at gov.cdc.prime.router.FakeReport.buildMappedColumn$prime_router(FakeReport.kt:289)
	at gov.cdc.prime.router.FakeReport.buildRow(FakeReport.kt:299)
	at gov.cdc.prime.router.FakeReport.build(FakeReport.kt:318)
	at gov.cdc.prime.router.cli.ProcessData.run(ProcessDataCommands.kt:355)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:204)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:213)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:17)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:396)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:393)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:411)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:436)
	at gov.cdc.prime.router.cli.MainKt.main(main.kt:269)

**Comment by oslynn** [comment]
Upon investigation, the finding is below:
$ ./prime data --input-fake 100 --input-schema ipatientCare/reddyfmc-la-covid-19 --output ./fake-reddy.csv
            . Still throw exception: Exception in thread "main" java.lang.IllegalStateException: Element type is null for message_id
    **Solution is to either add the message_id element to the IPatientCare-covid-19.schema to make it get the element from the covid-19.schema.**

Item 1) BUG: in fake data generator defaults don't work with TABLE types.
            . `createFakeTableValue `function doesn't know how to handle default correctly.  
            .  For the table start with "LIVD-SAR_CoV-2", it needs element.tableColumn to lookupTable.lookupValue
            . For the "LIVD-Supplemental", it needs element.tableColumn to NOT null and it will return the element.default if provided.
    **Solution: add code to handle element.default if provided and not element.tableColumn provided.**
Item 2)  BUG: with CODE types.
            . This is fixed.
Item 3) BUG: fake data generator does not know about the zip-code-data table.
            . The `zip-code-data` table handler is not implemented yet.
    **Solution: to add code to handle the zip-code-data table**
Item 4) BUG: creatFakeText doesn't handle sender_id's default value correctly.
    **Solution: add code to handle the default if provided.**
