### ISSUE TITLE
Bug: failure when SkipSend combined with HL7 single-message receivers.

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#2249]
Bug:  The SkipSend option fails when used with submissions with more than one record going to an HL7 receiver that expects a single message at a time.

Yes, this is pretty obscure, and yes this took a lot of experimenting to find!

Kudos to @carlosfelix2 for first noticing this when testing `./prime test --run parallel`

Steps to reproduce:
```
# First generate multiline (that's crucial!!) fake data going to our test rcvr IG.HL7
./prime data --input-fake 10 --input-schema primedatainput/pdi-covid-19 --output ./sr.csv --target-counties HL7 --target-states IG

# This should work fine, without the SkipSend option:
curl -X POST -H "client:simple_report"  -H "content-type:text/csv" --data-binary "@./sr.csv" "http://localhost:7071/api/reports"

# Now run the same submit, but with the SkipSend option on:
curl -X POST -H "client:simple_report"  -H "content-type:text/csv" --data-binary "@./sr.csv" "http://localhost:7071/api/reports?option=SkipSend"

#That now fails, with the exception down below , and with this response:
{"error": "Internal error at 2021-09-18T16:30:03.749035Z"}C02XQ6BDJG5J:p DKIQ$ 
```

The bug is in sendToDestination in ReportFunction.kt.    You'll see the secretive splitting of the HL7 occurs only when -> the data is to be sent immediately, and not when the option is SkipSend.

Note that this spitting in ReportFunction is quite a hack anyway - the batch function also does splitting, in the non-send-immediately cases.  Sigh.   I think the right solution is to ALWAYS call the batch function 100% of the time, and don't skip over it.   Then you can just delete the hack split()ting code in sendToDestination, knowing that Batch will take care of it.

(And is it confusing that the Batch function does splitting as well as merging?   Yes!!   It should be renamed the TimedRelease function or something.)

```
prime_dev_1     | [2021-09-18T15:48:19.148Z] Got exception while dispatching to schema tx/tx-covid-19, and rcvr ignore.HL7_NULL
prime_dev_1     | [2021-09-18T15:48:19.166Z] Internal Error: multiple item report cannot be written as a single HL7 message
prime_dev_1     | [2021-09-18T15:48:19.167Z] Result: Internal Error: multiple item report cannot be written as a single HL7 message
prime_dev_1     | [2021-09-18T15:48:19.168Z] Exception: Internal Error: multiple item report cannot be written as a single HL7 message
prime_dev_1     | [2021-09-18T15:48:19.169Z] Stack: java.lang.IllegalStateException: Internal Error: multiple item report cannot be written as a single HL7 message
prime_dev_1     | [2021-09-18T15:48:19.170Z] 	at gov.cdc.prime.router.serializers.Hl7Serializer.write(Hl7Serializer.kt:87)
prime_dev_1     | [2021-09-18T15:48:19.171Z] 	at gov.cdc.prime.router.azure.BlobAccess.createBodyBytes(BlobAccess.kt:104)
prime_dev_1     | [2021-09-18T15:48:19.172Z] 	at gov.cdc.prime.router.azure.BlobAccess.uploadBody(BlobAccess.kt:71)
prime_dev_1     | [2021-09-18T15:48:19.173Z] 	at gov.cdc.prime.router.azure.WorkflowEngine.dispatchReport(WorkflowEngine.kt:102)
prime_dev_1     | [2021-09-18T15:48:19.175Z] 	at gov.cdc.prime.router.azure.ReportFunction.sendToDestination(ReportFunction.kt:458)
prime_dev_1     | [2021-09-18T15:48:19.176Z] 	at gov.cdc.prime.router.azure.ReportFunction.access$sendToDestination(ReportFunction.kt:43)
prime_dev_1     | [2021-09-18T15:48:19.177Z] 	at gov.cdc.prime.router.azure.ReportFunction$routeReport$1.invoke(ReportFunction.kt:431)
prime_dev_1     | [2021-09-18T15:48:19.177Z] 	at gov.cdc.prime.router.azure.ReportFunction$routeReport$1.invoke(ReportFunction.kt:421)
prime_dev_1     | [2021-09-18T15:48:19.177Z] 	at gov.cdc.prime.router.azure.DatabaseAccess.transact$lambda-0(DatabaseAccess.kt:72)
prime_dev_1     | [2021-09-18T15:48:19.177Z] 	at org.jooq.impl.DefaultDSLContext.lambda$transaction$5(DefaultDSLContext.java:611)
prime_dev_1     | [2021-09-18T15:48:19.177Z] 	at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:549)
prime_dev_1     | [2021-09-18T15:48:19.177Z] 	at org.jooq.impl.Tools$4$1.block(Tools.java:5243)
prime_dev_1     | [2021-09-18T15:48:19.177Z] 	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
prime_dev_1     | [2021-09-18T15:48:19.177Z] 	at org.jooq.impl.Tools$4.get(Tools.java:5240)
prime_dev_1     | [2021-09-18T15:48:19.177Z] 	at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:597)
prime_dev_1     | [2021-09-18T15:48:19.177Z] 	at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:521)
prime_dev_1     | [2021-09-18T15:48:19.177Z] 	at org.jooq.impl.DefaultDSLContext.transaction(DefaultDSLContext.java:610)
prime_dev_1     | [2021-09-18T15:48:19.177Z] 	at gov.cdc.prime.router.azure.DatabaseAccess.transact(DatabaseAccess.kt:72)
prime_dev_1     | [2021-09-18T15:48:19.177Z] 	at gov.cdc.prime.router.azure.ReportFunction.routeReport(ReportFunction.kt:421)
prime_dev_1     | [2021-09-18T15:48:19.177Z] 	at gov.cdc.prime.router.azure.ReportFunction.ingestReport(ReportFunction.kt:164)
prime_dev_1     | [2021-09-18T15:48:19.177Z] 	at gov.cdc.prime.router.azure.ReportFunction.run(ReportFunction.kt:86)

```

**Comment by JGreenFearless** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/2249?planning-poker) with ZenHub @carlosfelix2 @jh765 @jimduff-usds @oslynn @smythe5 @whytheplatypus
