### ISSUE TITLE
equipment_model_name not found in Pima device_type alt valueset lookup causes Exception

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#2354]
The Pima Schema has a field not found in other schemas, called device_type.    device_type has an alt valueset that maps from equipment_model_name to alternate test labelling strings that are useful to them.   However, as new tests have come on the market, Pima is getting equipment_model_names not found in the table, which is throwing an exception.

(NOTE: THIS INITIAL FIX HAS BEEN DONE:  Add the equipment_model_names that are causing errors to the valueset in the AZ/pima schema.  There are two of these so far -- see the detailed exceptions attached as comments below.)

THIS IS THE WORK THAT NEEDS TO BE DONE:  This should not throw an exception.  If the field is not required, (which it isn't) it should zero-out the value if the input equipment_model_name is not found.

This is a good example of why we need the table/valuesets in the database, that @carlosfelix2 is working on.

FYI @MauriceReeves-usds 

A/C
Include a unit test

**Comment by jimduff-usds** [comment]
Exception thrown on Sat Sept 25:

```
Result: Batch function exception for event: receiver&BATCH&pima-az-phd.elr&2021-09-25T09:15:00-04:00
Exception: Schema Error: 'Sienna-Clarity COVID-19 Antigen Rapid Test Cassette*' is not in altValues set for 'Device_type' ('device_type')
Stack: java.lang.IllegalStateException: Schema Error: 'Sienna-Clarity COVID-19 Antigen Rapid Test Cassette*' is not in altValues set for 'Device_type' ('device_type')
	at gov.cdc.prime.router.Element.toFormatted(Element.kt:264)
	at gov.cdc.prime.router.serializers.CsvSerializer.write$buildRows(CsvSerializer.kt:203)
	at gov.cdc.prime.router.serializers.CsvSerializer.write(CsvSerializer.kt:212)
	at gov.cdc.prime.router.azure.BlobAccess.createBodyBytes(BlobAccess.kt:106)
	at gov.cdc.prime.router.azure.BlobAccess.uploadBody(BlobAccess.kt:71)
	at gov.cdc.prime.router.azure.WorkflowEngine.dispatchReport(WorkflowEngine.kt:102)
	at gov.cdc.prime.router.azure.BatchFunction$run$1.invoke(BatchFunction.kt:65)
	at gov.cdc.prime.router.azure.BatchFunction$run$1.invoke(BatchFunction.kt:40)
	at gov.cdc.prime.router.azure.WorkflowEngine$handleReceiverEvent$1.invoke(WorkflowEngine.kt:334)
	at gov.cdc.prime.router.azure.WorkflowEngine$handleReceiverEvent$1.invoke(WorkflowEngine.kt:301)
	at gov.cdc.prime.router.azure.DatabaseAccess.transact$lambda-0(DatabaseAccess.kt:72)
	at org.jooq.impl.DefaultDSLContext.lambda$transaction$5(DefaultDSLContext.java:611)
	at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:549)
	at org.jooq.impl.Tools$4$1.block(Tools.java:5243)
	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
	at org.jooq.impl.Tools$4.get(Tools.java:5240)
	at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:597)
	at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:521)
	at org.jooq.impl.DefaultDSLContext.transaction(DefaultDSLContext.java:610)
	at gov.cdc.prime.router.azure.DatabaseAccess.transact(DatabaseAccess.kt:72)
	at gov.cdc.prime.router.azure.WorkflowEngine.handleReceiverEvent(WorkflowEngine.kt:301)
	at gov.cdc.prime.router.azure.BatchFunction.run(BatchFunction.kt:40)
	at jdk.internal.reflect.GeneratedMethodAccessor203.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
	at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:55)
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:57)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by jimduff-usds** [comment]
And here's the different equipment_model_name that caused the Exception on Sept 23:

```
Result: Batch function exception for event: receiver&BATCH&pima-az-phd.elr&2021-09-23T09:15:00-04:00
Exception: Schema Error: 'Sofia 2 Flu + SARS Antigen FIA*' is not in altValues set for 'Device_type' ('device_type')
Stack: java.lang.IllegalStateException: Schema Error: 'Sofia 2 Flu + SARS Antigen FIA*' is not in altValues set for 'Device_type' ('device_type')
	at gov.cdc.prime.router.Element.toFormatted(Element.kt:264)
	at gov.cdc.prime.router.serializers.CsvSerializer.write$buildRows(CsvSerializer.kt:203)
	at gov.cdc.prime.router.serializers.CsvSerializer.write(CsvSerializer.kt:212)
	at gov.cdc.prime.router.azure.BlobAccess.createBodyBytes(BlobAccess.kt:106)
	at gov.cdc.prime.router.azure.BlobAccess.uploadBody(BlobAccess.kt:71)
	at gov.cdc.prime.router.azure.WorkflowEngine.dispatchReport(WorkflowEngine.kt:102)
	at gov.cdc.prime.router.azure.BatchFunction$run$1.invoke(BatchFunction.kt:66)
	at gov.cdc.prime.router.azure.BatchFunction$run$1.invoke(BatchFunction.kt:40)
	at gov.cdc.prime.router.azure.WorkflowEngine$handleReceiverEvent$1.invoke(WorkflowEngine.kt:322)
	at gov.cdc.prime.router.azure.WorkflowEngine$handleReceiverEvent$1.invoke(WorkflowEngine.kt:301)
	at gov.cdc.prime.router.azure.DatabaseAccess.transact$lambda-0(DatabaseAccess.kt:72)
	at org.jooq.impl.DefaultDSLContext.lambda$transaction$5(DefaultDSLContext.java:611)
	at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:549)
	at org.jooq.impl.Tools$4$1.block(Tools.java:5209)
	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
	at org.jooq.impl.Tools$4.get(Tools.java:5206)
	at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:597)
	at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:521)
	at org.jooq.impl.DefaultDSLContext.transaction(DefaultDSLContext.java:610)
	at gov.cdc.prime.router.azure.DatabaseAccess.transact(DatabaseAccess.kt:72)
	at gov.cdc.prime.router.azure.WorkflowEngine.handleReceiverEvent(WorkflowEngine.kt:301)
	at gov.cdc.prime.router.azure.BatchFunction.run(BatchFunction.kt:40)
	at jdk.internal.reflect.GeneratedMethodAccessor289.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
	at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:55)
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:57)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by jimduff-usds** [comment]
For the Sept 23 exception I found the data with this query:

`select * from covid_result_metadata where created_at > now() - interval '5 days' and equipment_model = 'Sofia 2 Flu + SARS Antigen FIA*' and patient_state = 'AZ';`

Incoming report_id = 621b0121-c3d0-4091-8f0e-6be25a149363

**Comment by jimduff-usds** [comment]
@mlighdc mentioned today that a facility in Pima county will be experiment with the new Uploader tool.  Undoubtedly they'll use new/different test devices that don't appear in this Alt list, which will trigger this error again if we don't fix it.

 @MauriceReeves-usds we may have to approach Pima at some point and ask to just get rid of this.   Or maybe add it to the LIVD-Supplemental table.

**Comment by mlighdc** [comment]
@jimduff-usds the good news about the pilot partner in Pima County is that she is currently entering results into SimpleReport so in the short term, the testing devices should be there. They conduct like 300 tests so she is looking to avoid double entry since they have their own EMR-type software.

Yes, for the full roll-out, devices could be an issue. Thanks for flagging.

**Comment by jimduff-usds** [comment]
This bug just occurred again today.
