### ISSUE TITLE
Exception thrown in SecretClient.getSecret attempting to reach the secrets store in azure

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#2566]
This exception seems to occur sporadically; I'm guessing maybe once or twice a month.

I don't _think_ it has anything to do with Redox (?); its an inability to reach the Secrets vault.

```
Result: Exception during REDOX send of reportId 4bd76d8e-0e06-4d5b-b135-50c74726b443:   Status code 401, "{"error":{"code":"Unauthorized","message":"[TokenExpired] Error validating token: 'S2S12086'."}}".  
Exception: Status code 401, "{"error":{"code":"Unauthorized","message":"[TokenExpired] Error validating token: 'S2S12086'."}}"
Stack: com.azure.core.exception.HttpResponseException: Status code 401, "{"error":{"code":"Unauthorized","message":"[TokenExpired] Error validating token: 'S2S12086'."}}"
```
The 401 appears to be a response from the vault:
```
Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1704)
		at com.azure.security.keyvault.secrets.SecretClient.getSecretWithResponse(SecretClient.java:179)
		at com.azure.security.keyvault.secrets.SecretClient.getSecret(SecretClient.java:157)
		at gov.cdc.prime.router.secrets.AzureSecretService.fetchSecretFromStore(AzureSecretService.kt:28)
		at gov.cdc.prime.router.secrets.SecretService.fetchSecret(SecretService.kt:14)
		at gov.cdc.prime.router.transport.RedoxTransport.getKeyAndSecret(RedoxTransport.kt:162)

```

**Comment by ronaldheft-usds** [comment]
This is an ongoing problem. The application recovers from this, but it's annoying an appears to be a bug in Azure.

**Comment by cwinters-usds** [comment]
Possibly related to #3116 ?
