### ISSUE TITLE
BlobAlreadyExists error in Batch step

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#2794]
(I do not think fixing this is a `good-first-issue`, however, examining the latest instance of it on Dec 8 2022 would be a fantastic `good-first-investigation` of a bug)

On Oct 27, 2021 at 07:15am ET, 
- Batch action 335887 merged a8d6c29f-8643-4c74-9687-fb0cc1f923ec and a8c4c851-2748-4510-b478-36f3a77cce1e into one hl7 file to send to oh-doh
- _At the exact same time_, Batch action 335890 merged `bb5b88c8-62dc-4ef8-8121-0edc87f2774e` and `9f10bbb9-9eec-4bd3-a324-ce016c0ee17f` into one hl7 file to send to oh-doh.

You can find this by doing:
`select * from action where action_params = 'receiver&BATCH&oh-doh.elr&2021-10-27T03:15:00-04:00'`

Because this happened within the same second, and because oh-doh marks their files by timestamp without mills, this caused this exception:
 `Exception: Status code 409, BlobAlreadyExists
`
If the quantity of work is greater than the batch size limit for a receiver, the system will run multiple BatchFunction for that receiver simultaneously.  And if the receiver has file naming rules that cause conflicts, this error can happen.   The most common file naming rule problem is using timestamps in filenames that only go down to the second, and with no uuid.   

Note that this error previously occasionally occurred during the receive step, however we fixed that issue #2279. This time it is occurring during the batch step, which is a different problem..

### Proposed Solution

Simply increment the timestamp forward one second until a name is found that doesn't cause a conflict.

A fancier solution would be to put the report's uuid into the filename in all cases of internal files, then change the filename just before its sent.  However this will break the very nice fact (a requirement, IMO)  that, for a given receiver, the download site (which shows internal files) shows _exactly_ the same filenames as sent via sftp.  Also, you would still need a way to disambiguate the files when you send them!

FYI @MauriceReeves-usds

**Comment by jimduff-usds** [comment]
This error occurred again today, Dec 27, 2021, in Production, for OH Secondary:

Result: Batch function exception for event: receiver&BATCH&oh-doh.elr-secondary&2021-12-27T15:15:00-05:00
Exception: Status code 409, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.

**Comment by jimduff-usds** [comment]
This problem occurred 14 times in the last 3 days, for oh-doh, and now nm-doh, which I had not seen before.

Here's the full exception:
```
Result: BatchFunction Exception (msg=receiver&BATCH&nm-doh.elr, backstopTime=2022-01-31T15:15:00.625293Z) : 
Exception: Status code 409, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:c01742c3-201e-0004-6000-172f08000000
Time:2022-02-01T00:15:23.6412458Z</Message></Error>"
Stack: com.azure.storage.blob.models.BlobStorageException: Status code 409, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:c01742c3-201e-0004-6000-172f08000000
Time:2022-02-01T00:15:23.6412458Z</Message></Error>"
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:389)
	at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$7(RestProxy.java:444)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:337)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:354)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onSubscribe(MonoCacheTime.java:293)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:192)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:143)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:119)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:184)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:128)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:400)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:419)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:473)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:702)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1372)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1246)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1286)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1707)
		at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:128)
		at com.azure.storage.blob.BlobClient.uploadWithResponse(BlobClient.java:303)
		at com.azure.storage.blob.BlobClient.uploadWithResponse(BlobClient.java:264)
		at com.azure.storage.blob.BlobClient.upload(BlobClient.java:211)
		at com.azure.storage.blob.BlobClient.upload(BlobClient.java:191)
		at gov.cdc.prime.router.azure.BlobAccess.uploadBlob(BlobAccess.kt:122)
		at gov.cdc.prime.router.azure.BlobAccess.uploadBlob$default(BlobAccess.kt:114)
		at gov.cdc.prime.router.azure.BlobAccess.uploadBody(BlobAccess.kt:96)
		at gov.cdc.prime.router.azure.BlobAccess.uploadBody(BlobAccess.kt:72)
		at gov.cdc.prime.router.azure.WorkflowEngine.dispatchReport(WorkflowEngine.kt:215)
		at gov.cdc.prime.router.azure.BatchFunction$run$1.invoke(BatchFunction.kt:93)
		at gov.cdc.prime.router.azure.BatchFunction$run$1.invoke(BatchFunction.kt:53)
		at gov.cdc.prime.router.azure.WorkflowEngine$handleBatchEvent$1.invoke(WorkflowEngine.kt:629)
		at gov.cdc.prime.router.azure.WorkflowEngine$handleBatchEvent$1.invoke(WorkflowEngine.kt:596)
		at gov.cdc.prime.router.azure.DatabaseAccess.transact$lambda-0(DatabaseAccess.kt:73)
		at org.jooq.impl.DefaultDSLContext.lambda$transaction$5(DefaultDSLContext.java:611)
		at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:549)
		at org.jooq.impl.Tools$4$1.block(Tools.java:5243)
		at java.base/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
		at org.jooq.impl.Tools$4.get(Tools.java:5240)
		at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:597)
		at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:521)
		at org.jooq.impl.DefaultDSLContext.transaction(DefaultDSLContext.java:610)
		at gov.cdc.prime.router.azure.DatabaseAccess.transact(DatabaseAccess.kt:73)
		at gov.cdc.prime.router.azure.WorkflowEngine.handleBatchEvent(WorkflowEngine.kt:596)
		at gov.cdc.prime.router.azure.BatchFunction.run(BatchFunction.kt:53)
		at jdk.internal.reflect.GeneratedMethodAccessor318.invoke(Unknown Source)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.base/java.lang.reflect.Method.invoke(Unknown Source)
		at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
		at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:55)
		at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:57)
		at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
		at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
		at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
		at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
		at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
		... 1 more
 ```

**Comment by jimduff-usds** [comment]
This error occurred again on Thurs Dec 8, 2022 at 3:47pm ET.
