### ISSUE TITLE
Bug: calling sender reqtoken returns errors

### ISSUE THREAD

**Issue by jbiskie** [CDCgov/prime-reportstream#3430]
**Describe the bug**
Calling `./prime sender reqtoken {...}`  returns a 404 error.
Calling the request token endpoint returns a 500 eror.

**Impact**
Token authentication does not work.

**To Reproduce**

_404 error:_

1. Follow steps 1a, 1b, and 2 as described in [how-to-use-token-auth](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/playbooks/how-to-use-token-auth.md)
2. In step 2, the `./prime sender reqtoken {...}` call returns a 404.  The URL it calls is `http://servername/token/?scope={...}` instead of `http://servername/api/token/?scope={...}`

_500 error:_

1. After following the steps above, make a REST call to the corrected URL above.  It returns a 500 Internal Server Error.  The stack trace is:

```Executing 'Functions.token' (Reason='This function was programmatically called via the host APIs.', Id=f38e4e33-c965-4f07-a844-2be62b6f6456)
Executed 'Functions.token' (Failed, Id=f38e4e33-c965-4f07-a844-2be62b6f6456, Duration=5ms)
System.Private.CoreLib: Exception while executing function: Functions.token. System.Private.CoreLib: Result: Failure
Exception: NoSuchMethodException: gov.cdc.prime.router.azure.TokenFunction.<init>()
Stack: java.lang.InstantiationException: gov.cdc.prime.router.azure.TokenFunction
        at java.base/java.lang.Class.newInstance(Class.java:571)
        at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.lambda$execute$1(EnhancedJavaMethodExecutorImpl.java:55)
        at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:20)
        at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:55)
        at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:57)
        at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
        at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
        at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
        at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoSuchMethodException: gov.cdc.prime.router.azure.TokenFunction.<init>()
        at java.base/java.lang.Class.getConstructor0(Class.java:3349)
        at java.base/java.lang.Class.newInstance(Class.java:556)
        ... 13 more
```

**Expected behavior**
The API call should return a bearer token as described in [how-to-use-token-auth](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/playbooks/how-to-use-token-auth.md).

**Comment by jbiskie** [comment]
This issue was resolved with PR #3439 on 12/13/21.
