### ISSUE TITLE
All In One Health and Uploader schemas are not testable.

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#3738]
We cannot test whether our system works on A1H and Uploader data, because we cannot generate fake data for them.

Both appear to have multiple layers of problems with them.   Below is the initial exception for each, but there's an untold number of exceptions hidden behind this.

If you create or modify a schema, you should generate fake data for it, because that's necessary for our system to do happy-path testing on it automatically, and for other people to test a schema when they are developing a new feature.

```
$ ./prime data --input-fake 1 --input-schema  non-standard/all-in-one-health-ca-covid-19 --output ./junk/a1h.csv

Exception in thread "main" java.lang.IllegalStateException: Element type is null for test_performed_code_temp
        at gov.cdc.prime.router.FakeDataService.getFakeValueForElement(FakeReport.kt:206)
        at gov.cdc.prime.router.FakeReport.buildColumn$prime_router(FakeReport.kt:265)
        at gov.cdc.prime.router.FakeReport.buildRow(FakeReport.kt:313)
        at gov.cdc.prime.router.FakeReport.build(FakeReport.kt:334)
        at gov.cdc.prime.router.cli.ProcessData.run(ProcessDataCommands.kt:372)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
        at gov.cdc.prime.router.cli.MainKt.main(main.kt:276)


$ ./prime data --input-fake 100 --input-schema upload-covid-19 --output ./junk/upload.csv

Exception in thread "main" java.lang.IllegalStateException: Element type is null for filler_order_id_temp
        at gov.cdc.prime.router.FakeDataService.getFakeValueForElement(FakeReport.kt:206)
        at gov.cdc.prime.router.FakeReport.buildColumn$prime_router(FakeReport.kt:265)
        at gov.cdc.prime.router.FakeReport.buildRow(FakeReport.kt:313)
        at gov.cdc.prime.router.FakeReport.build(FakeReport.kt:334)
        at gov.cdc.prime.router.cli.ProcessData.run(ProcessDataCommands.kt:372)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
        at gov.cdc.prime.router.cli.MainKt.main(main.kt:276)
```

**Comment by rhood23699** [comment]
Jim, Joel showed me why this is happening.  The Std CSV Schema with the necessary changes will be deployed Tuesday.  I'll work on A1H today.

**Comment by rhood23699** [comment]
These schemas are fixed in the next deployment.
