### ISSUE TITLE
Index out of bounds error in `Report.kt`

### ISSUE THREAD

**Issue by JosiahSiegel** [CDCgov/prime-reportstream#4375]
**Describe the bug**
Index out of bounds error in `Report.kt`

**Impact**
Unknown impact. 15 index out of bound exceptions logged in a few seconds @ `2/15/2022, 1:52:20 PM`

**Logs**
 * [Transaction Details](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%2C%22ResourceGroup%22%3A%22prime-data-hub-prod%22%2C%22Name%22%3A%22pdhprod-appinsights%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F7d1e3999-6577-4cd5-b296-f518e5c8e677%252FresourceGroups%252Fprime-data-hub-prod%252Fproviders%252Fmicrosoft.insights%252Fcomponents%252Fpdhprod-appinsights%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22eventId%22%3A%226e026bd1-8e90-11ec-83a1-37d572057363%22%2C%22timestamp%22%3A%222022-02-15T18%3A52%3A20.571Z%22%2C%22cacheId%22%3A%22dd4646b9-cc77-4576-832e-7ad8747585e7%22%2C%22eventTable%22%3A%22exceptions%22%7D)
 * [Log rows](https://portal.azure.com/#blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F7d1e3999-6577-4cd5-b296-f518e5c8e677%2FresourceGroups%2Fprime-data-hub-prod%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fpdhprod-appinsights/source/AIExtension.SearchV2/query/union%20isfuzzy%3Dtrue%20exceptions%0A%20%20%20%20%7C%20where%20timestamp%20%3E%20datetime(%222022-02-14T20%3A02%3A12.781Z%22)%20and%20timestamp%20%3C%20datetime(%222022-02-15T20%3A02%3A12.781Z%22)%7C%20where%20outerMessage%20in%20(%22Exception%20while%20executing%20function%3A%20Functions.process%22)%7C%20order%20by%20timestamp%20desc%7C%20take%20100/prettify/1)

```sh
Exception: Index 80 out of bounds for length 80
Stack: java.lang.IndexOutOfBoundsException: Index 80 out of bounds for length 80
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at gov.cdc.prime.router.Report.createTable$valuesToColumns(Report.kt:316)
	at gov.cdc.prime.router.Report.createTable(Report.kt:320)
	at gov.cdc.prime.router.Report.<init>(Report.kt:247)
	at gov.cdc.prime.router.Report.<init>(Report.kt:230)
```

**Comment by jimduff-usds** [comment]
This occurred in the process step, reading in an internal CSV file.

My first suspicion would be that we added or removed a column from the covid-19.schema in the latest release.

**Comment by RickHawesUSDS** [comment]
@jimduff-usds I would agree with your suspicion.

**Comment by jimduff-usds** [comment]
This is a known issue ticketed as #2571

**Comment by jorg3lopez** [comment]
It appears this happens when there is a schema change. The date for the error fall within the range that the deployment started and was finalized. This issue is being discussed with multiple teams, I will resend the test results and update the ticket once I do.

**Comment by jorg3lopez** [comment]
Asked Simple Report for the message_ids to be resent.
