### ISSUE TITLE
LIVD table update tool throws exception

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#5600]
When trying to run the LIVD download CLI command on 5/26/2022, I got an exception as follows.  I am unable to run the tool.

```
C:\dev\jdk-13\bin\java.exe "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\idea_rt.jar=55152:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\bin" -Dfile.encoding=UTF-8 @C:\Users\Carlos-Felix\AppData\Local\Temp\idea_arg_file1587145870 gov.cdc.prime.router.cli.MainKt livd-table-download -a --env staging
Downloading the LIVD table ...
Exception in thread "main" tech.tablesaw.io.ColumnIndexOutOfBoundsException: An IndexOutOfBoundsException occurred while detecting column types from row 27 with values: [Abbott, BinaxNOW COVID-19 Ag Card Home Test, SARS-CoV-2 nucleocapsid protein antigen, anterior nasal (nares) swab (697989009^Anterior nares swab^SCT), COVID-19 was detected (260373001^Detected^SCT)
COVID-19 was not detected (260415000^Not Detected^SCT)
Invalid (455371000124106^Invalid result^SCT or 125154007^Specimen unsatisfactory for evaluation^SCT), 94558-4, SARS-CoV-2 (COVID-19) Ag [Presence] in Respiratory specimen by Rapid immunoassay, 94558-4, SARS-CoV-2 (COVID-19) Ag [Presence] in Respiratory specimen by Rapid immunoassay, null, null, null, 10811877011337, DIT, 10811877011337, DII, SARS coronavirus 2 Ag, PrThr, Pt, Respiratory, Ord, IA.rapid, 20210303, 2.68, Home, H, M, W, Antigen, Lateral Flow, Lateral Flow, Visual Read, Over the Counter (OTC) Home Testing, Telehealth Proctor Supervised, Serial Screening, Single Target, yes, yes, null, null, null, yes, null, null, null, Visual Read, Single Target, null, null, null, null, null, null, yes, null, null, yes, yes]: Index 46 out of bounds for length 46
	at tech.tablesaw.io.ColumnTypeDetector.detectColumnTypes(ColumnTypeDetector.java:97)
	at tech.tablesaw.io.FileReader.getColumnTypes(FileReader.java:58)
	at tech.tablesaw.io.csv.CsvReader.detectColumnTypes(CsvReader.java:156)
	at tech.tablesaw.io.csv.CsvReader.getReaderAndColumnTypes(CsvReader.java:71)
	at tech.tablesaw.io.csv.CsvReader.read(CsvReader.java:92)
	at tech.tablesaw.io.csv.CsvReader.read(CsvReader.java:84)
	at tech.tablesaw.io.csv.CsvReader.read(CsvReader.java:30)
	at tech.tablesaw.io.DataFrameReader.usingOptions(DataFrameReader.java:152)
	at gov.cdc.prime.router.cli.LivdTableDownload.mergeLivdSupplementalTable(LivdTableDownload.kt:276)
	at gov.cdc.prime.router.cli.LivdTableDownload.run(LivdTableDownload.kt:103)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
	at gov.cdc.prime.router.cli.MainKt.main(main.kt:278)
Caused by: java.lang.IndexOutOfBoundsException: Index 46 out of bounds for length 46
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:373)
	at java.base/java.util.ArrayList.get(ArrayList.java:425)
	at tech.tablesaw.io.ColumnTypeDetector.detectColumnTypes(ColumnTypeDetector.java:86)
	... 17 more

Process finished with exit code 1

```

**Comment by brick-green** [comment]
did some debugging. The out of bounds execption is coming from the file reader. It bases the column count on the first record. For some reason, it is only counting 46 columns all the way until row 29 when it finds more than 46 then throws the exception. If you open the file manually it has 50 columns
