### ISSUE TITLE
Hook up the table `receiver_connection_check_results` to an api endpoint

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#5679]
This table is checking that receivers are working on a CRON job.

We need an API so we can create a dashboard that shows current status for each.

Features:
- API (require admin credentials for now. Future: Non-admins will ONLY match their organization_id)
- List operation (GET) returns rows for the past N-hrs (e.g 24hrs).
   Query includes DateRange for `[connection_check_started_at]` or defaults to last 24hrs.
- Maybe cgi parameter option to NOT include `connection_check_result`?

Schema:
```sql
create table receiver_connection_check_results (
    receiver_connection_check_result_id bigint  default nextval('receiver_connection_check_res_receiver_connection_check_res_seq'::regclass) not null
        primary key,
    organization_id                     integer                                                                                              not null
        references setting
            on delete cascade,
    receiver_id                         integer                                                                                              not null
        references setting
            on delete cascade,
    connection_check_result             text                                                                                                 not null,
    connection_check_successful         boolean default false                                                                                not null,
    connection_check_started_at         timestamp with time zone                                                                             not null,
    connection_check_completed_at       timestamp with time zone                                                                             not null
);
```

Example Data:
```
31,58,229,"ms-doh.elr: SFTP Transport: SFTPTransportType(host=sftp, port=22, filePath=./upload, credentialName=DEFAULT-SFTP)
ms-doh.elr: sftp: No root cause
java.net.UnknownHostException: sftp
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at net.schmizz.sshj.SocketClient.connect(SocketClient.java:68)
	at gov.cdc.prime.router.transport.SftpTransport$Companion.connect(SftpTransport.kt:140)
	at gov.cdc.prime.router.transport.SftpTransport$Companion.connect(SftpTransport.kt:105)
	at gov.cdc.prime.router.azure.CheckFunction.testSftp(CheckFunction.kt:252)
	at gov.cdc.prime.router.azure.CheckFunction.testTransport(CheckFunction.kt:217)
	at gov.cdc.prime.router.azure.CheckFunction.scheduledRun(CheckFunction.kt:141)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
	at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:55)
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:57)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**** ms-doh.elr: FAILED",false,2022-05-26 18:12:08.265371 +00:00,2022-05-26 18:12:08.271446 +00:00
245,58,229,"ms-doh.elr: SFTP Transport: SFTPTransportType(host=sftp, port=22, filePath=./upload, credentialName=DEFAULT-SFTP)
ms-doh.elr: Able to Connect to sftp site
ms-doh.elr: Success: ls returned 0 rows of info from SFTP Transport
**** ms-doh.elr: OK",true,2022-06-01 19:52:41.757438 +00:00,2022-06-01 19:52:42.167107 +00:00
```

Once API is in place, the web client will create a dashboard page to show Red/Yellow/Green for each result (based on # succeeded/failed). Clicking on a top-level Organization will lead to a Details List page.

**Comment by TomNUSDS** [comment]
@mauricereeves Anything to add?

**Comment by TomNUSDS** [comment]
I'm doing the work on this (see https://github.com/CDCgov/prime-reportstream/pull/6115 draft). But once it's done, I'd love to get the server-side code reviewed by someone on the pipeline team.
