### ISSUE TITLE
IG HL7 receiver throws send exceptions when processing a report of 40 items in staging

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-reportstream#612]
**Describe the bug**
IG HL7 receiver throws send exceptions when processing a report of 40 items in staging

**Impact**
Send exceptions indicate a unhandled logic error in our code. Tests are not being sent properly.  

**To Reproduce**
I’m able to consistently recreate this by sending a fake file of 40 Items in SimpleReport CSV format to STAGING with --target-states IG --target-counties HL7

**Expected behavior**
No send exceptions

**Logs**
```
2021-03-05T19:59:18.217115164Z: [INFO]        Function "send" (Id: 79a39189-86d3-4cc0-988d-cb391ac3a64e) invoked by Java Worker
2021-03-05T19:59:18.218126464Z: [INFO]  [40m[32minfo[39m[22m[49m: Function.send[2]
2021-03-05T19:59:18.218145564Z: [INFO]        Executed 'Functions.send' (Succeeded, Id=79a39189-86d3-4cc0-988d-cb391ac3a64e, Duration=35861ms)
2021-03-05T19:59:18.221850265Z: [INFO]  [41m[30mfail[39m[22m[49m: Function.send.User[0]
2021-03-05T19:59:18.221866765Z: [INFO]        Send exception
2021-03-05T19:59:18.221871865Z: [INFO]  Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException: Result: Send exception
2021-03-05T19:59:18.221876165Z: [INFO]  Exception: Error getting connection from data source HikariDataSource (HikariPool-3)
2021-03-05T19:59:18.221880165Z: [INFO]  Stack: org.jooq.exception.DataAccessException: Error getting connection from data source HikariDataSource (HikariPool-3)
2021-03-05T19:59:18.222872765Z: [INFO]         at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:90)
2021-03-05T19:59:18.222880165Z: [INFO]         at org.jooq.impl.DefaultTransactionProvider.connection(DefaultTransactionProvider.java:137)
2021-03-05T19:59:18.222884165Z: [INFO]         at org.jooq.impl.DefaultTransactionProvider.brace(DefaultTransactionProvider.java:238)
2021-03-05T19:59:18.222887965Z: [INFO]         at org.jooq.impl.DefaultTransactionProvider.begin(DefaultTransactionProvider.java:151)
2021-03-05T19:59:18.222891665Z: [INFO]         at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$0(DefaultDSLContext.java:537)
2021-03-05T19:59:18.222895665Z: [INFO]         at org.jooq.impl.Tools$35$1.block(Tools.java:5203)
2021-03-05T19:59:18.222899365Z: [INFO]         at java.base/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
2021-03-05T19:59:18.222903065Z: [INFO]         at org.jooq.impl.Tools$35.get(Tools.java:5200)
2021-03-05T19:59:18.222906765Z: [INFO]         at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:595)
2021-03-05T19:59:18.222910565Z: [INFO]         at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:512)
2021-03-05T19:59:18.222914365Z: [INFO]         at org.jooq.impl.DefaultDSLContext.transaction(DefaultDSLContext.java:612)
2021-03-05T19:59:18.222918065Z: [INFO]         at gov.cdc.prime.router.azure.DatabaseAccess.transact(DatabaseAccess.kt:57)
2021-03-05T19:59:18.222921765Z: [INFO]         at gov.cdc.prime.router.azure.WorkflowEngine.handleReportEvent(WorkflowEngine.kt:118)
2021-03-05T19:59:18.222925565Z: [INFO]         at gov.cdc.prime.router.azure.SendFunction.run(SendFunction.kt:44)
2021-03-05T19:59:18.222929265Z: [INFO]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-03-05T19:59:18.222942265Z: [INFO]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2021-03-05T19:59:18.222946065Z: [INFO]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2021-03-05T19:59:18.222949765Z: [INFO]         at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2021-03-05T19:59:18.222953465Z: [INFO]         at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
2021-03-05T19:59:18.222965165Z: [INFO]         at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:55)
2021-03-05T19:59:18.222971265Z: [INFO]         at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:57)
2021-03-05T19:59:18.222975365Z: [INFO]         at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
2021-03-05T19:59:18.222979265Z: [INFO]         at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
2021-03-05T19:59:18.222983065Z: [INFO]         at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
2021-03-05T19:59:18.222987765Z: [INFO]         at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
2021-03-05T19:59:18.222991765Z: [INFO]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
2021-03-05T19:59:18.222995565Z: [INFO]         at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
2021-03-05T19:59:18.222999265Z: [INFO]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2021-03-05T19:59:18.223003065Z: [INFO]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2021-03-05T19:59:18.223006865Z: [INFO]         at java.base/java.lang.Thread.run(Unknown Source)
2021-03-05T19:59:18.223010565Z: [INFO]         Suppressed: org.jooq.exception.DataAccessException: Cannot rollback transaction
2021-03-05T19:59:18.223014365Z: [INFO]                 at org.jooq.impl.DefaultConnectionProvider.rollback(DefaultConnectionProvider.java:129)
2021-03-05T19:59:18.223018165Z: [INFO]                at org.jooq.impl.DefaultTransactionProvider.rollback(DefaultTransactionProvider.java:213)
2021-03-05T19:59:18.223021965Z: [INFO]                   at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$0(DefaultDSLContext.java:567)
2021-03-05T19:59:18.223025965Z: [INFO]                  ... 25 more
2021-03-05T19:59:18.223029665Z: [INFO]                  Caused by: org.postgresql.util.PSQLException: Cannot rollback when autoCommit is enabled.
2021-03-05T19:59:18.223033465Z: [INFO]                         at org.postgresql.jdbc.PgConnection.rollback(PgConnection.java:895)
2021-03-05T19:59:18.223037165Z: [INFO]                        at com.zaxxer.hikari.pool.ProxyConnection.rollback(ProxyConnection.java:396)
2021-03-05T19:59:18.223040865Z: [INFO]                           at com.zaxxer.hikari.pool.HikariProxyConnection.rollback(HikariProxyConnection.java)
2021-03-05T19:59:18.223044565Z: [INFO]                          at org.jooq.impl.DefaultConnectionProvider.rollback(DefaultConnectionProvider.java:126)
2021-03-05T19:59:18.223048365Z: [INFO]                             ... 27 more
2021-03-05T19:59:18.223052065Z: [INFO]  Caused by: java.sql.SQLTransientConnectionException: HikariPool-3 - Connection is not available, request timed out after 30001ms.
2021-03-05T19:59:18.223055865Z: [INFO]         at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
2021-03-05T19:59:18.223059565Z: [INFO]         at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
2021-03-05T19:59:18.223066765Z: [INFO]         at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
2021-03-05T19:59:18.223070965Z: [INFO]         at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
2021-03-05T19:59:18.223074865Z: [INFO]         at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:87)
2021-03-05T19:59:18.223078565Z: [INFO]         ... 29 more
2021-03-05T19:59:18.223082265Z: [INFO]
```

**Comment by RickHawesUSDS** [comment]
I measured the duration of the send function as I varied the size of the reports. A couple points to understand this table.
- The work done by the send function is to send one HL7 message in all rows.
- The count is the size of the initial report. The batch function splits the report into single HL7 messages.
- The split causes a send function invocation storm, where 1-40 function invokes happen with a couple milliseconds of each other.
- The null transport is special benchmarking transport that doesn't sending bytes, but does same action history. 

Where | Transport | Count | Max Send Duration
-- | -- | -- | --
Staging | SFTP | 1 | 1.65
Staging | SFTP | 2 | 2.5
Staging | SFTP | 10 | 17
Staging | SFTP | 40 | Send Exceptions
  |   |   |  
Local | SFTP | 1 | 0.40
Local | SFTP | 2 | 0.43
Local | SFTP | 10 | 0.8
Local | SFTP | 40 | 2.350
  |   |   |  
Local | Null | 1 | 0.052
Local | Null | 2 | 0.069
Local | Null | 10 | 0.190
Local | Null | 40 | 0.378
  |   |   |  
Staging | Null | 1 | 0.060
Staging | Null | 2 | 0.168
Staging | Null | 10 | 0.345
Staging | Null | 40 | 0.699

**Comment by RickHawesUSDS** [comment]
There is a throughput bottleneck when sending single HL7 messages in staging. The bottleneck is doesn't appear to be caused by our DB overhead (although the DB overhead is not ideal).

**Comment by RickHawesUSDS** [comment]
Working on a PR.

**Comment by RickHawesUSDS** [comment]
Closing in favor of the batch queuing proposal.
