### ISSUE TITLE
prime sender-files to retrieve the sender's file is broken.

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-reportstream#6580]
The prime cli for getting sender's file using message_id is broken.  It needs to be look into it.

Error messages:
./prime sender-files --env prod --message-id 9e60a9c2-1cd1-440f-8de3-c6e22335429a -o ./junk/from_storage
Exception in thread "main" java.lang.StackOverflowError
	at com.github.ajalt.clikt.parameters.options.FlagOption.getValue(FlagOption.kt:41)
	at com.github.ajalt.clikt.parameters.options.OptionDelegate$DefaultImpls.getValue(Option.kt:91)
	at com.github.ajalt.clikt.parameters.options.FlagOption.getValue(FlagOption.kt:24)
	at com.github.ajalt.clikt.parameters.options.FlagOption.getValue(FlagOption.kt:24)
	at gov.cdc.prime.router.cli.SenderFilesCommand.getSilent(SenderFilesCommand.kt:79)
	at gov.cdc.prime.router.cli.SenderFilesCommand.echo(SenderFilesCommand.kt:219)
	at gov.cdc.prime.router.cli.SenderFilesCommand.echo(SenderFilesCommand.kt:219)
	at gov.cdc.prime.router.cli.SenderFilesCommand.echo(SenderFilesCommand.kt:219)

**Comment by BerniXiongA6** [comment]
Hi @oslynn thanks for writing this ticket, please correct me if I'm wrong... is this a bug? And could you update the ticket to let us know what's the ask for this ticket? Investigate to understand the fix? Fix it if we already know the problem? Or something else? You don't have to take on the ticket, but if you could edit the problem statement and acceptance criteria, that would be very helpful. Thank you!

**Comment by brick-green** [comment]
closing as duplicate ticket
