### ISSUE TITLE
UP needs to record item lineage correctly for HL7 Batch messages

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#7356]
### User Story:
As a sender, I want ReportStream to correctly record the item lineage of my full-ELR data, so I can keep track of my data.

### Description/Use Case
The UP has been processing only HL7 single message files, but it is capable of processing HL7 batch files.  Looks like there is an issue recording the item lineage correctly when the convert step is processing a batch file.  We need the UP to successfully process and record HL7 batch data.

### Dev Notes:
* The convert process is the one that splits the HL7 messages, so this is the step that needs to record the item lineage correctly.
* When sending a batch message to the UP I get this error:
```
Exception: IllegalStateException: There are child reports (dbfc0970-f77f-4311-a0de-c6345060f8a1) but no item lineages
...
Caused by: java.lang.IllegalStateException: There are child reports (dbfc0970-f77f-4311-a0de-c6345060f8a1) but no item lineages
[2022-11-14T15:39:30.603Z] 	at gov.cdc.prime.router.azure.ActionHistory.generateReportLineagesUsingItemLineage$prime_router(ActionHistory.kt:643)
[2022-11-14T15:39:30.604Z] 	at gov.cdc.prime.router.azure.ActionHistory.generateLineages(ActionHistory.kt:214)
[2022-11-14T15:39:30.604Z] 	at gov.cdc.prime.router.azure.DatabaseAccess.saveActionHistoryToDb(DatabaseAccess.kt:1244)
[2022-11-14T15:39:30.604Z] 	at gov.cdc.prime.router.azure.WorkflowEngine$recordAction$1.invoke(WorkflowEngine.kt:697)
[2022-11-14T15:39:30.604Z] 	at gov.cdc.prime.router.azure.WorkflowEngine$recordAction$1.invoke(WorkflowEngine.kt:697)
```

### Acceptance Criteria
* The UP can process an HL7 batch file submitted by a sender.
* The UP records the proper lineage of the individual HL7 messages in an HL7 batch file.

**Comment by carlosfelix2** [comment]
[https://app.zenhub.com/files/304423150/7ea14fba-93ab-4935-88d7-366bbea22b06/download](https://app.zenhub.com/files/304423150/7ea14fba-93ab-4935-88d7-366bbea22b06/download)

**Comment by bishoyayoub** [comment]
@arnejduranovic Please review and let us know if this is still needed.
