### ISSUE TITLE
Investigate CO-PHD.ELR-SECONDARY Failure since Fri, 2/24/2023, 8:16 PM

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-reportstream#8494]
Org:
co-phd (id: 1439)
Receiver:
elr-secondary (id: 1598)
Result:
failed
Started At:
Fri, 2/24/2023, 8:16 PM
2023-02-25T02:16:00.836Z
Time to complete:
00.18s
Result message:
**** Receiver Status: ACTIVE co-phd.elr-secondary: SFTP Transport: SFTPTransportType(host=test.moveit.state.co.us, port=22, filePath=./, credentialName=null) co-phd.elr-secondary: Connection reset: Connection reset net.schmizz.sshj.transport.TransportException: Connection reset at net.schmizz.sshj.transport.TransportImpl.init(TransportImpl.java:165) at net.schmizz.sshj.SSHClient.onConnect(SSHClient.java:793) at net.schmizz.sshj.SocketClient.connect(SocketClient.java:139) at gov.cdc.prime.router.transport.SftpTransport$Companion.connect(SftpTransport.kt:140) at gov.cdc.prime.router.transport.SftpTransport$Companion.connect(SftpTransport.kt:105) at gov.cdc.prime.router.azure.CheckFunction.testSftp(CheckFunction.kt:400) at gov.cdc.prime.router.azure.CheckFunction.testTransport(CheckFunction.kt:315) at gov.cdc.prime.router.azure.CheckFunction.scheduledRun(CheckFunction.kt:240) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22) at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:55) at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:62) at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33) at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10) at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45) at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:829) Caused by: java.net.SocketException: Connection reset at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186) at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140) at java.base/java.net.SocketInputStream.read(SocketInputStream.java:200) at net.schmizz.sshj.transport.TransportImpl.receiveServerIdent(TransportImpl.java:182) at net.schmizz.sshj.transport.TransportImpl.init(TransportImpl.java:158) ... 23 more **** co-phd.elr-secondary: FAILED

**Comment by oslynn** [comment]
Emailed to STLT:
============
Kecso - CDPHE, Nancy <nancy.kecso@state.co.us>;andrew.horvath@state.co.us
Report Stream (CDC);brandoncanniff@navapbc.com;Green, Brick (CDC/DDPHSS/OD/HITSSU) (CTR);james.gilmore@agile6.com
Good morning, Nancy, Andrew,

My name is OTT SATHNGAM, CDC ReportStream Engineer.  I notice the connection between ReportStream and co-phd.elr-secondary failed since Fri, 2/24/2023, 8:16 PM.

Do you know what is going on with the channel?  
Did the channel been turned off and no longer needed?  
Is there any configuration or software update to the channel?  

Would you please let me know?

Very respectfully and thank you for your help
-Ott Sathngam
CDC ReportStream Eng.

**Comment by oslynn** [comment]
Status response from CO-PHD.ELR-SECONDARY:

ecso - CDPHE, Nancy <nancy.kecso@state.co.us>
Sathngam, Ott (CDC/DDPHSS/OD/HITSSU)
andrew.horvath@state.co.us;Report Stream (CDC);brandoncanniff@navapbc.com;Green, Brick (CDC/DDPHSS/OD/HITSSU) (CTR);james.gilmore@agile6.com
Ott,

Thank you for the alert.  The connections have been down all weekend.  I have sent out an alert and will let you know as soon as things are back to normal.

Nancy

**Comment by oslynn** [comment]
Kecso - CDPHE, Nancy <nancy.kecso@state.co.us>
Sathngam, Ott (CDC/DDPHSS/OD/HITSSU)
andrew.horvath@state.co.us;Report Stream (CDC);brandoncanniff@navapbc.com;Green, Brick (CDC/DDPHSS/OD/HITSSU) (CTR);james.gilmore@agile6.com
Ott:

Things are back running.  

There was one file from CDC that was queued and it has been processed.  The filename is covid-19-a5929a61-aac4-4a6f-93be-3f0b6983d988-20230225023027.hl7

Nancy

**Comment by oslynn** [comment]
Nancy,

I just resubmitted 8 messages that was in the co-phd.elr-secondary prod feed.

Again thank you for your help,  If anything we can, please let you us know.

-Ott Sathngam
CDC ReportStream Eng.

'=====
The issue is being fixed.  I restored and tested the channel and it is good to do.  I then resubmitted all messages that failed to send.  Therefore, the ticket is closed.
