### ISSUE TITLE
Investigate ID failure and lost connection since 3/20/2023 at 5:15 PM

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-reportstream#8836]
'=== Last mile failure ===
Receiving Org:
id-phd.elr
Failed at:
Thu, 3/23/2023, 5:34 PM
Action ID:
23677826
Report ID:
938aa445-947a-48cc-996f-68db002355e9
Report File Receiver:
id-phd.elr
File URI:
https://pdhprodstorageaccount.blob.core.windows.net/reports/ready%2Fid-phd.elr%2Fcovid-19-938aa445-947a-48cc-996f-68db002355e9-20230322051537.hl7
id-phd.elr
Results:
FAILED Sftp upload of inputReportId 938aa445-947a-48cc-996f-68db002355e9 to SFTPTransportType(host=sftp.dhw.idaho.gov, port=22, filePath=./ELR/SimpleReport/Prod, credentialName=null) (orgService = id-phd.elr), Exception: Exhausted available authentication methods, All retries failed. Manual Intervention Required. Send Error report for: 938aa445-947a-48cc-996f-68db002355e9 to id-phd.elr

'==== Connection failed ====
Org:
id-phd (id: 1080)
Receiver:
elr (id: 1343)
Result:
failed
Started At:
Mon, 3/20/2023, 5:15 PM
2023-03-20T22:15:06.652Z
Time to complete:
07.653s
Result message:
**** Receiver Status: ACTIVE id-phd.elr: SFTP Transport: SFTPTransportType(host=sftp.dhw.idaho.gov, port=22, filePath=./ELR/SimpleReport/Prod, credentialName=null) id-phd.elr: Exhausted available authentication methods: No root cause net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods at net.schmizz.sshj.SSHClient.auth(SSHClient.java:227) at net.schmizz.sshj.SSHClient.auth(SSHClient.java:202) at net.schmizz.sshj.SSHClient.authPassword(SSHClient.java:288) at net.schmizz.sshj.SSHClient.authPassword(SSHClient.java:258) at net.schmizz.sshj.SSHClient.authPassword(SSHClient.java:242) at gov.cdc.prime.router.transport.SftpTransport$Companion.connect(SftpTransport.kt:142) at gov.cdc.prime.router.transport.SftpTransport$Companion.connect(SftpTransport.kt:105) at gov.cdc.prime.router.azure.CheckFunction.testSftp(CheckFunction.kt:400) at gov.cdc.prime.router.azure.CheckFunction.testTransport(CheckFunction.kt:315) at gov.cdc.prime.router.azure.CheckFunction.scheduledRun(CheckFunction.kt:240) at jdk.internal.reflect.GeneratedMethodAccessor1533.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22) at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:55) at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:62) at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33) at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10) at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45) at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:829) **** id-phd.elr: FAILED

**Comment by oslynn** [comment]
Now, ReportStream is using PPK to communicate with ID-PHD.ELR.  Therefore, it should not expired again.
