### ISSUE TITLE
UP: Add retry logic to pipeline steps

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#9149]
### User Story
As ReportStream, if a pipeline step fails I should be able to retry multiple times before giving up.

### Description/Use Case
The COVID pipeline has a similar task with https://github.com/CDCgov/prime-reportstream/issues/3535. 3535 mentions there is an "interim" solution for the COVID pipeline process step, see that ticket for more details. UP presently only has a retry mechanism for the batch step and we should design and implement something that is appropriate for the other steps. We should have a plan in place in the event that a step does ultimately fail.

### Dev Notes:
The Batch step has a decaying retry, see that code for more details if that is what we want to do for the other steps.

Note, we probably shouldn't blindly retry steps in the pipeline, maybe only retry in the case of an uncaught exception? This strategy will need to be thought through and evaluated before implementing.

### Acceptance Criteria
- [x] In the event of a failure, a step in the UP will get retried multiple times, if appropriate, before giving up.

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9149?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @JessicaWNava @jimmyfagan @mkalish @PatriciaPerozoUSDS @thetaurean @victor-chaparro @TurkeyFried

**Comment by mkalish** [comment]
Jotting some notes down:
- There likely isn't a ton of work here, since we get automatic retries for anything pulled off the queue
- The thing to check for is if there is anywhere that we swallow an exception that should result in a retry, unhandled exception is what determines if message should go back into the queue
- The retry behavior for the batch step is a little specific to how that step works
  - Batch messages are generated based on the configured batch size count; for example if a STLT is configured to receive 2 messages per batch and there are 4 messages on the queue, 2 batch messages will get added
  - The retry functionality is how far back in time the BatchDeciderFunction will look back to determine what messages should be batched, this means that if an item fails to get into a batch because of the error the look back window will still pick it up two more times
  - This step differs though from the other steps where there is 1:1 situation

**Comment by mkalish** [comment]
Azurite cannot be configured for a specific retry policy and the default retries happen too quickly to turn the server on off.  However, it is possible to still see the retry behavior by throwing an exception at the beginning of the convert or route function to see the 5 times the message is processed

```
[2023-07-21T13:50:02.431Z] Executing 'Functions.route-fhir' (Reason='New queue message detected on 'elr-fhir-route'.', Id=068be5f7-c785-45c2-8ea8-5ba6a4b0624d)
[2023-07-21T13:50:02.432Z] Trigger Details: MessageId: f39aa02c-a2c8-42ad-b9a7-57a0dc0fc341, DequeueCount: 1, InsertionTime: 2023-07-21T13:50:01.000+00:00
[2023-07-21T13:50:02.466Z] Executed 'Functions.route-fhir' (Failed, Id=068be5f7-c785-45c2-8ea8-5ba6a4b0624d, Duration=21ms)
[2023-07-21T13:50:02.466Z] System.Private.CoreLib: Exception while executing function: Functions.route-fhir. System.Private.CoreLib: Result: Failure
[2023-07-21T13:50:02.466Z] Exception: RuntimeException: Early exit to test retry
[2023-07-21T13:50:02.466Z] Stack: java.lang.reflect.InvocationTargetException
[2023-07-21T13:50:02.466Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-07-21T13:50:02.466Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-07-21T13:50:02.466Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-07-21T13:50:02.466Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2023-07-21T13:50:02.466Z]      at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
[2023-07-21T13:50:02.466Z]      at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:55)
[2023-07-21T13:50:02.466Z]      at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:62)
[2023-07-21T13:50:02.466Z]      at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[2023-07-21T13:50:02.466Z]      at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[2023-07-21T13:50:02.466Z]      at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[2023-07-21T13:50:02.466Z]      at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[2023-07-21T13:50:02.466Z]      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2023-07-21T13:50:02.466Z]      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2023-07-21T13:50:02.466Z]      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2023-07-21T13:50:02.466Z]      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2023-07-21T13:50:02.466Z]      at java.base/java.lang.Thread.run(Thread.java:829)
[2023-07-21T13:50:02.466Z] Caused by: java.lang.RuntimeException: Early exit to test retry
[2023-07-21T13:50:02.466Z]      at gov.cdc.prime.router.fhirengine.azure.FHIRFunctions.route(FHIRFunctions.kt:74)
[2023-07-21T13:50:02.466Z]      ... 16 more
[2023-07-21T13:50:02.466Z] .
[2023-07-21T13:50:02.549Z] Executing 'Functions.route-fhir' (Reason='New queue message detected on 'elr-fhir-route'.', Id=2174e224-0521-4ce9-b83d-9ae5d879680a)
[2023-07-21T13:50:02.549Z] Trigger Details: MessageId: f39aa02c-a2c8-42ad-b9a7-57a0dc0fc341, DequeueCount: 2, InsertionTime: 2023-07-21T13:50:01.000+00:00
[2023-07-21T13:50:02.561Z] Executed 'Functions.route-fhir' (Failed, Id=2174e224-0521-4ce9-b83d-9ae5d879680a, Duration=8ms)
[2023-07-21T13:50:02.561Z] System.Private.CoreLib: Exception while executing function: Functions.route-fhir. System.Private.CoreLib: Result: Failure
[2023-07-21T13:50:02.561Z] Exception: RuntimeException: Early exit to test retry
[2023-07-21T13:50:02.561Z] Stack: java.lang.reflect.InvocationTargetException
[2023-07-21T13:50:02.561Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-07-21T13:50:02.561Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-07-21T13:50:02.561Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-07-21T13:50:02.561Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2023-07-21T13:50:02.561Z]      at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
[2023-07-21T13:50:02.561Z]      at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:55)
[2023-07-21T13:50:02.561Z]      at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:62)
[2023-07-21T13:50:02.561Z]      at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[2023-07-21T13:50:02.561Z]      at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[2023-07-21T13:50:02.561Z]      at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[2023-07-21T13:50:02.561Z]      at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[2023-07-21T13:50:02.561Z]      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2023-07-21T13:50:02.561Z]      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2023-07-21T13:50:02.561Z]      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2023-07-21T13:50:02.561Z]      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2023-07-21T13:50:02.561Z]      at java.base/java.lang.Thread.run(Thread.java:829)
[2023-07-21T13:50:02.561Z] Caused by: java.lang.RuntimeException: Early exit to test retry
[2023-07-21T13:50:02.561Z]      at gov.cdc.prime.router.fhirengine.azure.FHIRFunctions.route(FHIRFunctions.kt:74)
[2023-07-21T13:50:02.561Z]      ... 16 more
[2023-07-21T13:50:02.561Z] .
[2023-07-21T13:50:02.664Z] Executing 'Functions.route-fhir' (Reason='New queue message detected on 'elr-fhir-route'.', Id=9c50e9db-f62f-4564-84ce-81e14ad8e55a)
[2023-07-21T13:50:02.664Z] Trigger Details: MessageId: f39aa02c-a2c8-42ad-b9a7-57a0dc0fc341, DequeueCount: 3, InsertionTime: 2023-07-21T13:50:01.000+00:00
[2023-07-21T13:50:02.680Z] Executed 'Functions.route-fhir' (Failed, Id=9c50e9db-f62f-4564-84ce-81e14ad8e55a, Duration=13ms)
[2023-07-21T13:50:02.680Z] System.Private.CoreLib: Exception while executing function: Functions.route-fhir. System.Private.CoreLib: Result: Failure
[2023-07-21T13:50:02.680Z] Exception: RuntimeException: Early exit to test retry
[2023-07-21T13:50:02.680Z] Stack: java.lang.reflect.InvocationTargetException
[2023-07-21T13:50:02.680Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-07-21T13:50:02.680Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-07-21T13:50:02.680Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-07-21T13:50:02.680Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2023-07-21T13:50:02.680Z]      at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
[2023-07-21T13:50:02.680Z]      at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:55)
[2023-07-21T13:50:02.680Z]      at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:62)
[2023-07-21T13:50:02.680Z]      at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[2023-07-21T13:50:02.680Z]      at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[2023-07-21T13:50:02.680Z]      at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[2023-07-21T13:50:02.680Z]      at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[2023-07-21T13:50:02.680Z]      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2023-07-21T13:50:02.680Z]      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2023-07-21T13:50:02.680Z]      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2023-07-21T13:50:02.680Z]      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2023-07-21T13:50:02.680Z]      at java.base/java.lang.Thread.run(Thread.java:829)
[2023-07-21T13:50:02.680Z] Caused by: java.lang.RuntimeException: Early exit to test retry
[2023-07-21T13:50:02.680Z]      at gov.cdc.prime.router.fhirengine.azure.FHIRFunctions.route(FHIRFunctions.kt:74)
[2023-07-21T13:50:02.680Z]      ... 16 more
[2023-07-21T13:50:02.680Z] .
[2023-07-21T13:50:02.781Z] Executing 'Functions.route-fhir' (Reason='New queue message detected on 'elr-fhir-route'.', Id=f2974530-bce2-4259-9d73-fbe3cb7a3dd9)
[2023-07-21T13:50:02.781Z] Trigger Details: MessageId: f39aa02c-a2c8-42ad-b9a7-57a0dc0fc341, DequeueCount: 4, InsertionTime: 2023-07-21T13:50:01.000+00:00
[2023-07-21T13:50:02.791Z] Executed 'Functions.route-fhir' (Failed, Id=f2974530-bce2-4259-9d73-fbe3cb7a3dd9, Duration=8ms)
[2023-07-21T13:50:02.791Z] System.Private.CoreLib: Exception while executing function: Functions.route-fhir. System.Private.CoreLib: Result: Failure
[2023-07-21T13:50:02.791Z] Exception: RuntimeException: Early exit to test retry
[2023-07-21T13:50:02.791Z] Stack: java.lang.reflect.InvocationTargetException
[2023-07-21T13:50:02.791Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-07-21T13:50:02.791Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-07-21T13:50:02.791Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-07-21T13:50:02.791Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2023-07-21T13:50:02.791Z]      at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
[2023-07-21T13:50:02.791Z]      at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:55)
[2023-07-21T13:50:02.791Z]      at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:62)
[2023-07-21T13:50:02.791Z]      at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[2023-07-21T13:50:02.791Z]      at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[2023-07-21T13:50:02.791Z]      at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[2023-07-21T13:50:02.791Z]      at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[2023-07-21T13:50:02.791Z]      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2023-07-21T13:50:02.791Z]      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2023-07-21T13:50:02.791Z]      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2023-07-21T13:50:02.791Z]      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2023-07-21T13:50:02.791Z]      at java.base/java.lang.Thread.run(Thread.java:829)
[2023-07-21T13:50:02.791Z] Caused by: java.lang.RuntimeException: Early exit to test retry
[2023-07-21T13:50:02.791Z]      at gov.cdc.prime.router.fhirengine.azure.FHIRFunctions.route(FHIRFunctions.kt:74)
[2023-07-21T13:50:02.791Z]      ... 16 more
[2023-07-21T13:50:02.791Z] .
[2023-07-21T13:50:02.894Z] Executing 'Functions.route-fhir' (Reason='New queue message detected on 'elr-fhir-route'.', Id=6376b846-4b38-4979-b476-dd2dfe8465ea)
[2023-07-21T13:50:02.894Z] Trigger Details: MessageId: f39aa02c-a2c8-42ad-b9a7-57a0dc0fc341, DequeueCount: 5, InsertionTime: 2023-07-21T13:50:01.000+00:00
[2023-07-21T13:50:02.904Z] Executed 'Functions.route-fhir' (Failed, Id=6376b846-4b38-4979-b476-dd2dfe8465ea, Duration=11ms)
[2023-07-21T13:50:02.904Z] System.Private.CoreLib: Exception while executing function: Functions.route-fhir. System.Private.CoreLib: Result: Failure
[2023-07-21T13:50:02.904Z] Exception: RuntimeException: Early exit to test retry
[2023-07-21T13:50:02.904Z] Stack: java.lang.reflect.InvocationTargetException
[2023-07-21T13:50:02.904Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-07-21T13:50:02.904Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-07-21T13:50:02.904Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-07-21T13:50:02.904Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2023-07-21T13:50:02.904Z]      at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
[2023-07-21T13:50:02.904Z]      at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:55)
[2023-07-21T13:50:02.904Z]      at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:62)
[2023-07-21T13:50:02.904Z]      at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[2023-07-21T13:50:02.904Z]      at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[2023-07-21T13:50:02.904Z]      at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[2023-07-21T13:50:02.904Z]      at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[2023-07-21T13:50:02.904Z]      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2023-07-21T13:50:02.904Z]      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2023-07-21T13:50:02.904Z]      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2023-07-21T13:50:02.904Z]      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2023-07-21T13:50:02.904Z]      at java.base/java.lang.Thread.run(Thread.java:829)
[2023-07-21T13:50:02.904Z] Caused by: java.lang.RuntimeException: Early exit to test retry
[2023-07-21T13:50:02.904Z]      at gov.cdc.prime.router.fhirengine.azure.FHIRFunctions.route(FHIRFunctions.kt:74)
[2023-07-21T13:50:02.904Z]      ... 16 more
[2023-07-21T13:50:02.905Z] .
[2023-07-21T13:50:02.907Z] Message has reached MaxDequeueCount of 5. Moving message to queue 'elr-fhir-route-poison'.
```

**Comment by mkalish** [comment]
Specifically, looking at the process step, the UP always processes in async mode; there is not a ton of work here as it almost immediately just puts a message on the convert queue and since this is HttpTrigger a retry might not make sense/ might have unintended consequences.

**Comment by mkalish** [comment]
I'm moving this to QA/Review as it's been documented and I'm not sure that there is any work to be done here.

cc/ @arnejduranovic

**Comment by mkalish** [comment]
Adding notes on the retry functionality for send as well.

There is a custom retry solution in the send step so that the application can track when there are issues sending as part of the action table.  It works similarly to how the azure queue messages are retried.  Each transport is responsible for catching any errors and returning whether or not the send should be retried.  The send function than calculates when it should be tried getting using an exponential backoff, retrying up to five times.
