### ISSUE TITLE
Investigate the compatibility issue between RS and Azure-storage-blob version 12.22.0

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-reportstream#9370]
The version 12.22.0 throws exception as following:

2023-05-02T15:14:19.445408759Z [2023-05-02T15:14:19.445Z] 	Suppressed: **java.lang.Exception**: #block terminated with an error
2023-05-02T15:14:19.445498265Z [2023-05-02T15:14:19.445Z] 		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99) ~[reactor-core-3.4.27.jar:3.4.27]
2023-05-02T15:14:19.445515717Z [2023-05-02T15:14:19.445Z] 		at reactor.core.publisher.Mono.block(Mono.java:1742) ~[reactor-core-3.4.27.jar:3.4.27]
2023-05-02T15:14:19.445523323Z [2023-05-02T15:14:19.445Z] 		at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:133) ~[azure-storage-common-12.21.0.jar:12.21.0]
2023-05-02T15:14:19.445532788Z [2023-05-02T15:14:19.445Z] 		at com.azure.storage.blob.BlobContainerClient.existsWithResponse(BlobContainerClient.java:263) ~[azure-storage-blob-12.22.0.jar:12.22.0]
2023-05-02T15:14:19.445553710Z [2023-05-02T15:14:19.445Z] 		at com.azure.storage.blob.BlobContainerClient.exists(BlobContainerClient.java:241) ~[azure-storage-blob-12.22.0.jar:12.22.0]
2023-05-02T15:14:19.445577487Z [2023-05-02T15:14:19.445Z] 		at gov.cdc.prime.router.azure.BlobAccess$Companion.getBlobContainer(BlobAccess.kt:193) ~[prime-router-0.2-SNAPSHOT.jar:?]
2023-05-02T15:14:19.445607990Z [2023-05-02T15:14:19.445Z] 		at gov.cdc.prime.router.azure.BlobAccess$Companion.uploadBlob$prime_router(BlobAccess.kt:127) ~[prime-router-0.2-SNAPSHOT.jar:?]
2023-05-02T15:14:19.445637478Z [2023-05-02T15:14:19.445Z] 		at gov.cdc.prime.router.azure.BlobAccess$Companion.uploadBlob$prime_router$default(BlobAccess.kt:120) ~[prime-router-0.2-SNAPSHOT.jar:?]
2023-05-02T15:14:19.445676127Z [2023-05-02T15:14:19.445Z] 		at gov.cdc.prime.router.azure.BlobAccess$Companion.uploadBody(BlobAccess.kt:104) ~[prime-router-0.2-SNAPSHOT.jar:?]
2023-05-02T15:14:19.445700661Z [2023-05-02T15:14:19.445Z] 		at gov.cdc.prime.router.azure.WorkflowEngine.recordReceivedReport(WorkflowEngine.kt:182) ~[prime-router-0.2-SNAPSHOT.jar:?]
2023-05-02T15:14:19.445720755Z [2023-05-02T15:14:19.445Z] 		at gov.cdc.prime.router.TopicReceiver.validateAndMoveToProcessing(SubmissionReceiver.kt:174) ~[prime-router-0.2-SNAPSHOT.jar:?]
2023-05-02T15:14:19.445749318Z [2023-05-02T15:14:19.445Z] 		at gov.cdc.prime.router.SubmissionReceiver.validateAndMoveToProcessing$default(SubmissionReceiver.kt:43) ~[prime-router-0.2-SNAPSHOT.jar:?]
2023-05-02T15:14:19.445806715Z [2023-05-02T15:14:19.445Z] 		at gov.cdc.prime.router.azure.ReportFunction.processRequest$prime_router(ReportFunction.kt:169) ~[prime-router-0.2-SNAPSHOT.jar:?]
2023-05-02T15:14:19.445826551Z [2023-05-02T15:14:19.445Z] 		at gov.cdc.prime.router.azure.ReportFunction.submitToWaters(ReportFunction.kt:107) ~[prime-router-0.2-SNAPSHOT.jar:?]
2023-05-02T15:14:19.445858899Z [2023-05-02T15:14:19.445Z] 		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
2023-05-02T15:14:19.445882779Z [2023-05-02T15:14:19.445Z] 		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
2023-05-02T15:14:19.445907265Z [2023-05-02T15:14:19.445Z] 		at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
2023-05-02T15:14:19.445968729Z [2023-05-02T15:14:19.445Z] 		at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
2023-05-02T15:14:19.445978798Z [2023-05-02T15:14:19.445Z] 		at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22) ~[azure-functions-java-worker.jar:2.8.1]
2023-05-02T15:14:19.446008063Z [2023-05-02T15:14:19.445Z] 		at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:22) ~[azure-functions-java-worker.jar:2.8.1]
2023-05-02T15:14:19.446045353Z [2023-05-02T15:14:19.445Z] 		at com.microsoft.azure.functions.worker.chain.FunctionExecutionMiddleware.invoke(FunctionExecutionMiddleware.java:19) ~[azure-functions-java-worker.jar:2.8.1]
2023-05-02T15:14:19.446091757Z [2023-05-02T15:14:19.446Z] 		at com.microsoft.azure.functions.worker.chain.InvocationChain.doNext(InvocationChain.java:21) ~[azure-functions-java-worker.jar:2.8.1]
2023-05-02T15:14:19.446105327Z [2023-05-02T15:14:19.446Z] 		at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:125) ~[azure-functions-java-worker.jar:2.8.1]
2023-05-02T15:14:19.446136126Z [2023-05-02T15:14:19.446Z] 		at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:37) ~[azure-functions-java-worker.jar:2.8.1]
2023-05-02T15:14:19.446160974Z [2023-05-02T15:14:19.446Z] 		at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:12) ~[azure-functions-java-worker.jar:2.8.1]
2023-05-02T15:14:19.446200160Z [2023-05-02T15:14:19.446Z] 		at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:44) ~[azure-functions-java-worker.jar:2.8.1]
2023-05-02T15:14:19.446260068Z [2023-05-02T15:14:19.446Z] 		at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:93) ~[azure-functions-java-worker.jar:2.8.1]
2023-05-02T15:14:19.446275897Z [2023-05-02T15:14:19.446Z] 		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
2023-05-02T15:14:19.446304732Z [2023-05-02T15:14:19.446Z] 		at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
2023-05-02T15:14:19.446331423Z [2023-05-02T15:14:19.446Z] 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
2023-05-02T15:14:19.446391307Z [2023-05-02T15:14:19.446Z] 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
2023-05-02T15:14:19.446416136Z [2023-05-02T15:14:19.446Z] 		at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by oslynn** [comment]
Same as the ticket 9169 - Bump com.azure:azure-storage-blob from 12.20.1 to 12.22.0.  And, I updated Azurite to 3.23.0 to be compatible with the azure-storage-blob above.   It is done.  Therefore, I am closing it.
