### ISSUE TITLE
Investigate phone number failure during FHIR to HL7 translation

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#9644]
### User Story
As a Reportstream user and developer, I want to know what criteria cause a phone number to fail the translation process. 

### Description/Use Case
Dig in and figure out what causes the failure, whether it is just checking against the zip code or something else. Also, make sure the submission history looks correct for when submitting it through the endpoint rather than the command line tool.

### Dev Notes
This happened when trying to translate a fhir to hl7 message using the command line tool. 
ex. `./prime fhirdata --input-file src/testIntegration/resources/datatests/FHIR_to_HL7/testfhir.fhir -s metadata/hl7_mapping/receivers/STLTs/CA/CA.yml --output-format HL7 --output-file src/testIntegration/resources/datatests/FHIR_to_HL7/testhl7.hl7
`
The phone number used in the message was 1 (000)000-0000
Stack trace below:
```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 1
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
        at java.base/java.lang.String.substring(String.java:1874)
        at gov.cdc.prime.router.fhirengine.translation.hl7.utils.PhoneUtilities.getPhoneNumberPart(PhoneUtilities.kt:36)
        at gov.cdc.prime.router.fhirengine.translation.hl7.utils.CustomFHIRFunctions.getPhoneNumberAreaCode(CustomFHIRFunctions.kt:195)
        at gov.cdc.prime.router.fhirengine.translation.hl7.utils.CustomFHIRFunctions.executeFunction(CustomFHIRFunctions.kt:136)
        at gov.cdc.prime.router.fhirengine.translation.hl7.utils.FhirPathCustomResolver.executeFunction(ConstantResolver.kt:184)
```

### Acceptance Criteria
- [ ] Submission history is checked for a message with the phone number submitted in a message through the API
- [ ] What causes the failure is understood and documented.

**Comment by arnejduranovic** [comment]
@JessicaWNava to update this ticket to handle the above scenario correctly.
