### ISSUE TITLE
RS failed to authenticate with WA-PHD.REST 

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-reportstream#9648]
Org:
wa-phd (id: 1360)
Receiver:
rest (id: 1733)
Result:
failed
Started At:
Tue, 5/30/2023, 1:17 PM
2023-05-30T18:17:16.724Z
Time to complete:
01.37s
Result message:
**** Receiver Status: ACTIVE wa-phd.rest: REST Transport Attempting to authenticate at: https://prd-v2-onehealthport-api.axwaycloud.com/ohp/oauth/jwt/token wa-phd.rest: Client request(POST https://prd-v2-onehealthport-api.axwaycloud.com/ohp/oauth/jwt/token) invalid: 401 Unauthorized. Text: "{ "reasons" : [ { "language" : "en", "message" : "{\"Error\": \"JWT is Invalid\"}" } ], "details" : { "msgId" : "Id-ad3d76640fe1e69e286a0d7a" } }": No root cause io.ktor.client.plugins.ClientRequestException: Client request(POST https://prd-v2-onehealthport-api.axwaycloud.com/ohp/oauth/jwt/token) invalid: 401 Unauthorized. Text: "{ "reasons" : [ { "language" : "en", "message" : "{\"Error\": \"JWT is Invalid\"}" } ], "details" : { "msgId" : "Id-ad3d76640fe1e69e286a0d7a" } }" at io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:54) at io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt) at io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt) at io.ktor.client.plugins.HttpCallValidator.validateResponse(HttpCallValidator.kt:51) at io.ktor.client.plugins.HttpCallValidator.access$validateResponse(HttpCallValidator.kt:43) at io.ktor.client.plugins.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:152) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284) at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85) at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) at gov.cdc.prime.router.azure.CheckFunction.testRest(CheckFunction.kt:357) at gov.cdc.prime.router.azure.CheckFunction.testTransport(CheckFunction.kt:316) at gov.cdc.prime.router.azure.CheckFunction.scheduledRun(CheckFunction.kt:240) at jdk.internal.reflect.GeneratedMethodAccessor1734.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22) at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:55) at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:62) at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33) at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10) at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45) at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:829) **** wa-phd.rest: FAILED

**Comment by oslynn** [comment]
Risler, Jenni K (DOH) <jennifer.risler@doh.wa.gov>;Thomas, Caroline R (DOH) <Caroline.Thomas@doh.wa.gov>;Vanderkolk, Julie (DOH) <Julie.Vanderkolk@doh.wa.gov>
lafredahoward@navapbc.com;brandoncanniff@navapbc.com;Report Stream (CDC);Green, Brick (CDC/DDPHSS/OD/HITSSU) (CTR)
Good after noon, Caroline,

Hope everything is going well for you and your team.

Somehow, ReportStream can't authenticate with wa-phd.rest and got invalid 401 Unauthorized code response.
It failed since Mon, 5/29/2023, 1:17 PM.  Is ReportStream certificate/key expired why it doesn't allow RS to authentication anymore?
Or your server is down?  Would you please let me know?

Very respectfully
-Ott Sathngam
CDC ReportStream Engineer

**Comment by oslynn** [comment]
Hello Ott,

 

This problem sounds similar to an issue USDS encountered last year.  Please see italicized text below.  I’ve cc’d Kelly from OHP for troubleshooting assistance.  Please let us know if you require additional assistance.
https://outlook.office365.com/mail/inbox/id/AAQkADY2ODFiNTg0LWYyZTItNDc0Ny1hNTg4LTdhYzAzOWVmYTczMgAQAMhhu26N0aJEhrSQo7ZZFj8%3D

**Comment by oslynn** [comment]
Hello everyone,

 

The CDC team is connected in Production to the HIE using the new JWT 2.0 OAuth token to send ELR messages to the Department of Health. On May 17, 2023 we sent a new Production token to replace the token that was set to expire on 5/29/2023. The new token was effective on 5/22/2023 with an expiration date of 11/22/2023. We sent this new token via secure mail to Thomas Greene.

 

@Greene, Thomas (CDC/DDPHSS/OD/HITSSU) did you receive this secure email with the new token? If you did, you should have replaced the old token. If you didn’t replace the token, that is why you cannot connect because you are using an expired token. We will resend this secure email with the new token to all the team members on this email thread at CDC. Would someone please be responsible for obtaining this token and getting it updated in your connectivity set up?

 

Thank you,

 

Kelly

Senior Account Manager

OneHealthPort

2003 Western Avenue, Suite 600

Seattle, WA 98121

Phone: 206-899-4824

Cell: 253-686-0929

kellyl@onehealthport.com

www.onehealthport.com

Home of the 12s and Superbowl XLVIII Champion Seattle Seahawks 

UW Huskies! Winner of the 2022 Apple Cup

**Comment by oslynn** [comment]
Excellent! Thank you for confirming Ott. 😊

 

Kelly

Senior Account Manager

OneHealthPort

2003 Western Avenue, Suite 600

Seattle, WA 98121

Phone: 206-899-4824

Cell: 253-686-0929

kellyl@onehealthport.com

www.onehealthport.com

Home of the 12s and Superbowl XLVIII Champion Seattle Seahawks 

UW Huskies! Winner of the 2022 Apple Cup

**Comment by oslynn** [comment]
Done.
