### ISSUE TITLE
[SPIKE] 2 Exceptions Received, needs investigation

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#9914]
## **Problem Statement**
Received a notification on 6/12/2023 Slack #prime-reportstream-onboarding-operations from Lucas Dze who is on PagerDuty on two Exceptions notifications.  Please see the below error message for more information:

## **What you need to know**
- The exceptions over the past 7 days (which include the ones listed below on 6/12) can be found in [this spreadsheet](https://docs.google.com/spreadsheets/d/1F3lJT6tNQIgAbo2ZHNqEG3m7gqf1CWCez5fk5KmOs5k/edit?usp=drive_link)

- Penny's latest addition of new tracking info should help solve this #9706

- From Slack:

> This exception just occurred in Prod:
> Error: React Router caught the following error during render
>     at console.Object.entries.forEach.e.<computed> [as error] (https://reportstream.cdc.gov/static/js/main.4ae5e5c3.js:2:3513670)
>     at n.value (https://reportstream.cdc.gov/static/js/main.4ae5e5c3.js:2:1116834)
>     at n.a.componentDidCatch.n.callback (https://reportstream.cdc.gov/static/js/main.4ae5e5c3.js:2:895538)
>     at Fa (https://reportstream.cdc.gov/static/js/main.4ae5e5c3.js:2:876716)
>     at wl (https://reportstream.cdc.gov/static/js/main.4ae5e5c3.js:2:924265)
>     at xl (https://reportstream.cdc.gov/static/js/main.4ae5e5c3.js:2:923835)
>     at xl (https://reportstream.cdc.gov/static/js/main.4ae5e5c3.js:2:923734)
>     at bl (https://reportstream.cdc.gov/static/js/main.4ae5e5c3.js:2:923373)
>     at https://reportstream.cdc.gov/static/js/main.4ae5e5c3.js:2:935157
>     at kc (https://reportstream.cdc.gov/static/js/main.4ae5e5c3.js:2:935668)

Brick Green reviewed the notification and referred this to be taken care by WebX Team.

## **Acceptance Criteria**
- [ ] Assign to a WebX Engineer
- [ ] Investigate the issue and determine what action (if any is needed).

**Comment by LaFreda1** [comment]
@sliu1000 I'm removing engagement. We can add our label if they need our support.

**Comment by chris-kuryak** [comment]
Stale. Likely no longer needed. Can check to ensure these exceptions are still happening.
